In [4]:
import helpers, api_request
import pandas as pd

In [5]:
api_request.HMS.login

In [6]:
api_request.HMS.login

In [3]:
#replacing COMIDS from new aoi
df_new_catch = pd.read_excel('NHDFlowlineV2_Merrimack_AttributeTable_Excel_CK_BC_KV.xlsx')
df_new_catch.head()

,FID,COMID,FDATE,RESOLUTION,GNIS_ID,GNIS_NAME,LENGTHKM,REACHCODE,FLOWDIR,WBAREACOMI,FTYPE,FCODE,SHAPE_LENG,ENABLED,GNIS_NBR
0,0,6741978,2008-07-21,Medium,619363,Merrimack River,1.123,1070006001801,With Digitized,120049678,ArtificialPath,55800,0.012973,True,0
1,1,6746018,2008-07-21,Medium,619363,Merrimack River,0.198,1070006000409,With Digitized,120049678,ArtificialPath,55800,0.001960,True,0
2,2,6741876,2008-07-21,Medium,619363,Merrimack River,1.962,1070006001810,With Digitized,120049678,ArtificialPath,55800,0.018477,True,0
3,3,6742162,2008-07-21,Medium,619363,Merrimack River,1.034,1070006000002,With Digitized,120049678,ArtificialPath,55800,0.011660,True,0
4,4,6741964,2008-07-21,Medium,619363,Merrimack River,1.397,1070006001803,With Digitized,120049678,ArtificialPath,55800,0.012969,True,0

In [4]:
new_list = df_new_catch['COMID'].tolist()[0:]
type(new_list)

list

In [7]:
#Back Creek COMID Selection Revising from the use of an excel file or csv as above to extract COMID list. 
#Now provides new listing formation 
new_list = [8625279,8625313,8625375,8625523,8625547,8625615,8625685,8625697,8625717,8625727,8625731,8625735,8625739,8625747,8625775,8627469,8628577,8628579,8628581,8628587,8628591,8628603,8628611,8628623,8628627,8628631,8628641,8628643,8629331]

In [8]:
new_list[0:5] #prints out first five COMIDs in list

[8625279, 8625313, 8625375, 8625523, 8625547]

In [9]:
 len(new_list) #Gets length of the comids in list

29

In [10]:
length = len(new_list)
#Identify how long the COMID list is
print(length)

29

In [11]:
#COMID List of Choice is set here (new from my watershed workflow)
comid_list =[]
comid_list.append(new_list)
print(comid_list)
length = len(comid_list[0])
#Identify how long the COMID list is
print(length) #double checking after resetting to the comid list

[[8625279, 8625313, 8625375, 8625523, 8625547, 8625615, 8625685, 8625697, 8625717, 8625727, 8625731, 8625735, 8625739, 8625747, 8625775, 8627469, 8628577, 8628579, 8628581, 8628587, 8628591, 8628603, 8628611, 8628623, 8628627, 8628631, 8628641, 8628643, 8629331]]
29

In [12]:
#https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=9731484 tester for single
#catch_char_url = ('https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=' + str(comid_list[0][0]))
catch_char_url = ('https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=' + str(comid_list[0][0]))
print(catch_char_url)
import requests
#catch_char_url = ('https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=' + str(comid[i]))
response1 = requests.get(catch_char_url)
print(response1.status_code)
print(response1.json())
catch_char = response1.json()
#catch_char_dic = json.loads(catch_char.json())
print(type(catch_char))
#print(catch_char['metadata']['BANKFULL_DEPTH'],catch_char['metadata']['BANKFULL_XSEC_AREA'], catch_char['metadata'])

https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8625279
200
{'metadata': {'FROMCOMID': '8625279', 'FROMHYDSEQ': '250021125', 'FROMLVLPAT': '250020754', 'TOCOMID': '8627469', 'TOHYDSEQ': '250020754', 'TOLVLPAT': '250020754', 'NODENUMBER': '250007866', 'DELTALEVEL': '0', 'DIRECTION': '709', 'GAPDISTKM': '0', 'HasGeo': 'Y', 'TotDASqKM': '151.992', 'DivDASqKM': '151.992', 'Region': '03N', 'ComID': '8625279', 'Fdate': '7/3/2012', 'StreamLeve': '2', 'StreamOrde': '3', 'StreamCalc': '3', 'FromNode': '250007202', 'ToNode': '250007866', 'Hydroseq': '250021125', 'LevelPathI': '250020754', 'Pathlength': '556.341', 'TerminalPa': '250002964', 'Divergence': '0', 'StartFlag': '0', 'TerminalFl': '0', 'DnLevel': '2', 'ThinnerCod': '0', 'UpLevelPat': '250020754', 'UpHydroseq': '250021525', 'DnLevelPat': '250020754', 'DnMinorHyd': '0', 'DnDrainCou': '1', 'DnHydroseq': '250020754', 'FromMeas': '1.91088', 'ToMeas': '100', 'ReachCode': '03010101000410', 'LengthKM': '2.41', 'Fcode': '46006', 'RtnDiv': '0', 'OutDiv': '0', 'DivEffect': '0', 'VPUIn': '0', 'VPUOut': '0', 'AreaSqKM': '2.133', 'Tidal': '0', 'TOTMA': '0.07607163305', 'WBAreaType': '', 'CentroidLatitude': '37.22526', 'CentroidLongitude': '-79.85560583', 'WBAREACOMI': 'NA', 'MAXELEVRAW': '-9998', 'MINELEVRAW': '24214', 'MAXELEVSMO': '24952', 'MINELEVSMO': '24337', 'SLOPE': '0.00255186', 'ELEVFIXED': '0', 'HWTYPE': '', 'STATUSFLAG': 'A', 'SLOPELENKM': '2.41', 'COMID': '8625279', 'REACHCODE': '03010101000410', 'HUC12': '030101010405', 'TOHUC': '030101010701', 'Length': '0.0', 'BANKFULL_WIDTH': '25.10', 'BANKFULL_DEPTH': '1.10', 'BANKFULL_XSEC_AREA': '28.17'}}
<class 'dict'>

In [14]:
catch_char['metadata'].keys() #list of all the parameters associated with the json request from HMS

dict_keys(['FROMCOMID', 'FROMHYDSEQ', 'FROMLVLPAT', 'TOCOMID', 'TOHYDSEQ', 'TOLVLPAT', 'NODENUMBER', 'DELTALEVEL', 'DIRECTION', 'GAPDISTKM', 'HasGeo', 'TotDASqKM', 'DivDASqKM', 'Region', 'ComID', 'Fdate', 'StreamLeve', 'StreamOrde', 'StreamCalc', 'FromNode', 'ToNode', 'Hydroseq', 'LevelPathI', 'Pathlength', 'TerminalPa', 'Divergence', 'StartFlag', 'TerminalFl', 'DnLevel', 'ThinnerCod', 'UpLevelPat', 'UpHydroseq', 'DnLevelPat', 'DnMinorHyd', 'DnDrainCou', 'DnHydroseq', 'FromMeas', 'ToMeas', 'ReachCode', 'LengthKM', 'Fcode', 'RtnDiv', 'OutDiv', 'DivEffect', 'VPUIn', 'VPUOut', 'AreaSqKM', 'Tidal', 'TOTMA', 'WBAreaType', 'CentroidLatitude', 'CentroidLongitude', 'WBAREACOMI', 'MAXELEVRAW', 'MINELEVRAW', 'MAXELEVSMO', 'MINELEVSMO', 'SLOPE', 'ELEVFIXED', 'HWTYPE', 'STATUSFLAG', 'SLOPELENKM', 'COMID', 'REACHCODE', 'HUC12', 'TOHUC', 'Length', 'BANKFULL_WIDTH', 'BANKFULL_DEPTH', 'BANKFULL_XSEC_AREA'])

In [18]:
type(catch_char['metadata'])

dict

In [19]:
new_data = catch_char['metadata']
type(new_data)

dict

In [41]:
new_data

{'FROMCOMID': '8625279',
 'FROMHYDSEQ': '250021125',
 'FROMLVLPAT': '250020754',
 'TOCOMID': '8627469',
 'TOHYDSEQ': '250020754',
 'TOLVLPAT': '250020754',
 'NODENUMBER': '250007866',
 'DELTALEVEL': '0',
 'DIRECTION': '709',
 'GAPDISTKM': '0',
 'HasGeo': 'Y',
 'TotDASqKM': '151.992',
 'DivDASqKM': '151.992',
 'Region': '03N',
 'ComID': '8625279',
 'Fdate': '7/3/2012',
 'StreamLeve': '2',
 'StreamOrde': '3',
 'StreamCalc': '3',
 'FromNode': '250007202',
 'ToNode': '250007866',
 'Hydroseq': '250021125',
 'LevelPathI': '250020754',
 'Pathlength': '556.341',
 'TerminalPa': '250002964',
 'Divergence': '0',
 'StartFlag': '0',
 'TerminalFl': '0',
 'DnLevel': '2',
 'ThinnerCod': '0',
 'UpLevelPat': '250020754',
 'UpHydroseq': '250021525',
 'DnLevelPat': '250020754',
 'DnMinorHyd': '0',
 'DnDrainCou': '1',
 'DnHydroseq': '250020754',
 'FromMeas': '1.91088',
 'ToMeas': '100',
 'ReachCode': '03010101000410',
 'LengthKM': '2.41',
 'Fcode': '46006',
 'RtnDiv': '0',
 'OutDiv': '0',
 'DivEffect': '0',
 'VPUIn': '0',
 'VPUOut': '0',
 'AreaSqKM': '2.133',
 'Tidal': '0',
 'TOTMA': '0.07607163305',
 'WBAreaType': '',
 'CentroidLatitude': '37.22526',
 'CentroidLongitude': '-79.85560583',
 'WBAREACOMI': 'NA',
 'MAXELEVRAW': '-9998',
 'MINELEVRAW': '24214',
 'MAXELEVSMO': '24952',
 'MINELEVSMO': '24337',
 'SLOPE': '0.00255186',
 'ELEVFIXED': '0',
 'HWTYPE': '',
 'STATUSFLAG': 'A',
 'SLOPELENKM': '2.41',
 'COMID': '8625279',
 'REACHCODE': '03010101000410',
 'HUC12': '030101010405',
 'TOHUC': '030101010701',
 'Length': '0.0',
 'BANKFULL_WIDTH': '25.10',
 'BANKFULL_DEPTH': '1.10',
 'BANKFULL_XSEC_AREA': '28.17'}

In [31]:
new_data.items()

dict_items([('FROMCOMID', '8625279'), ('FROMHYDSEQ', '250021125'), ('FROMLVLPAT', '250020754'), ('TOCOMID', '8627469'), ('TOHYDSEQ', '250020754'), ('TOLVLPAT', '250020754'), ('NODENUMBER', '250007866'), ('DELTALEVEL', '0'), ('DIRECTION', '709'), ('GAPDISTKM', '0'), ('HasGeo', 'Y'), ('TotDASqKM', '151.992'), ('DivDASqKM', '151.992'), ('Region', '03N'), ('ComID', '8625279'), ('Fdate', '7/3/2012'), ('StreamLeve', '2'), ('StreamOrde', '3'), ('StreamCalc', '3'), ('FromNode', '250007202'), ('ToNode', '250007866'), ('Hydroseq', '250021125'), ('LevelPathI', '250020754'), ('Pathlength', '556.341'), ('TerminalPa', '250002964'), ('Divergence', '0'), ('StartFlag', '0'), ('TerminalFl', '0'), ('DnLevel', '2'), ('ThinnerCod', '0'), ('UpLevelPat', '250020754'), ('UpHydroseq', '250021525'), ('DnLevelPat', '250020754'), ('DnMinorHyd', '0'), ('DnDrainCou', '1'), ('DnHydroseq', '250020754'), ('FromMeas', '1.91088'), ('ToMeas', '100'), ('ReachCode', '03010101000410'), ('LengthKM', '2.41'), ('Fcode', '46006'), ('RtnDiv', '0'), ('OutDiv', '0'), ('DivEffect', '0'), ('VPUIn', '0'), ('VPUOut', '0'), ('AreaSqKM', '2.133'), ('Tidal', '0'), ('TOTMA', '0.07607163305'), ('WBAreaType', ''), ('CentroidLatitude', '37.22526'), ('CentroidLongitude', '-79.85560583'), ('WBAREACOMI', 'NA'), ('MAXELEVRAW', '-9998'), ('MINELEVRAW', '24214'), ('MAXELEVSMO', '24952'), ('MINELEVSMO', '24337'), ('SLOPE', '0.00255186'), ('ELEVFIXED', '0'), ('HWTYPE', ''), ('STATUSFLAG', 'A'), ('SLOPELENKM', '2.41'), ('COMID', '8625279'), ('REACHCODE', '03010101000410'), ('HUC12', '030101010405'), ('TOHUC', '030101010701'), ('Length', '0.0'), ('BANKFULL_WIDTH', '25.10'), ('BANKFULL_DEPTH', '1.10'), ('BANKFULL_XSEC_AREA', '28.17')])

In [40]:
df_new_data = pd.DataFrame.from_dict(new_data.items())
df_new_data.head()

            0          1
0   FROMCOMID    8625279
1  FROMHYDSEQ  250021125
2  FROMLVLPAT  250020754
3     TOCOMID    8627469
4    TOHYDSEQ  250020754

In [46]:
df_nd_2 = df_new_data.transpose()

In [54]:
df_nd_2[0:-1][:].values

array([['FROMCOMID', 'FROMHYDSEQ', 'FROMLVLPAT', 'TOCOMID', 'TOHYDSEQ',
        'TOLVLPAT', 'NODENUMBER', 'DELTALEVEL', 'DIRECTION', 'GAPDISTKM',
        'HasGeo', 'TotDASqKM', 'DivDASqKM', 'Region', 'ComID', 'Fdate',
        'StreamLeve', 'StreamOrde', 'StreamCalc', 'FromNode', 'ToNode',
        'Hydroseq', 'LevelPathI', 'Pathlength', 'TerminalPa',
        'Divergence', 'StartFlag', 'TerminalFl', 'DnLevel', 'ThinnerCod',
        'UpLevelPat', 'UpHydroseq', 'DnLevelPat', 'DnMinorHyd',
        'DnDrainCou', 'DnHydroseq', 'FromMeas', 'ToMeas', 'ReachCode',
        'LengthKM', 'Fcode', 'RtnDiv', 'OutDiv', 'DivEffect', 'VPUIn',
        'VPUOut', 'AreaSqKM', 'Tidal', 'TOTMA', 'WBAreaType',
        'CentroidLatitude', 'CentroidLongitude', 'WBAREACOMI',
        'MAXELEVRAW', 'MINELEVRAW', 'MAXELEVSMO', 'MINELEVSMO', 'SLOPE',
        'ELEVFIXED', 'HWTYPE', 'STATUSFLAG', 'SLOPELENKM', 'COMID',
        'REACHCODE', 'HUC12', 'TOHUC', 'Length', 'BANKFULL_WIDTH',
        'BANKFULL_DEPTH', 'BANKFULL_XSEC_AREA']], dtype=object)

In [55]:
df_nd_2.keys = df_nd_2[0:-1][:].values

In [61]:
df_nd_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 70 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       2 non-null      object
 1   1       2 non-null      object
 2   2       2 non-null      object
 3   3       2 non-null      object
 4   4       2 non-null      object
 5   5       2 non-null      object
 6   6       2 non-null      object
 7   7       2 non-null      object
 8   8       2 non-null      object
 9   9       2 non-null      object
 10  10      2 non-null      object
 11  11      2 non-null      object
 12  12      2 non-null      object
 13  13      2 non-null      object
 14  14      2 non-null      object
 15  15      2 non-null      object
 16  16      2 non-null      object
 17  17      2 non-null      object
 18  18      2 non-null      object
 19  19      2 non-null      object
 20  20      2 non-null      object
 21  21      2 non-null      object
 22  22      2 non-null      object
 23  23      2 non-null      object
 24  24      2 non-null      object
 25  25      2 non-null      object
 26  26      2 non-null      object
 27  27      2 non-null      object
 28  28      2 non-null      object
 29  29      2 non-null      object
 30  30      2 non-null      object
 31  31      2 non-null      object
 32  32      2 non-null      object
 33  33      2 non-null      object
 34  34      2 non-null      object
 35  35      2 non-null      object
 36  36      2 non-null      object
 37  37      2 non-null      object
 38  38      2 non-null      object
 39  39      2 non-null      object
 40  40      2 non-null      object
 41  41      2 non-null      object
 42  42      2 non-null      object
 43  43      2 non-null      object
 44  44      2 non-null      object
 45  45      2 non-null      object
 46  46      2 non-null      object
 47  47      2 non-null      object
 48  48      2 non-null      object
 49  49      2 non-null      object
 50  50      2 non-null      object
 51  51      2 non-null      object
 52  52      2 non-null      object
 53  53      2 non-null      object
 54  54      2 non-null      object
 55  55      2 non-null      object
 56  56      2 non-null      object
 57  57      2 non-null      object
 58  58      2 non-null      object
 59  59      2 non-null      object
 60  60      2 non-null      object
 61  61      2 non-null      object
 62  62      2 non-null      object
 63  63      2 non-null      object
 64  64      2 non-null      object
 65  65      2 non-null      object
 66  66      2 non-null      object
 67  67      2 non-null      object
 68  68      2 non-null      object
 69  69      2 non-null      object
dtypes: object(70)
memory usage: 1.2+ KB

In [45]:
df_new_data.head()

            0          1
0   FROMCOMID    8625279
1  FROMHYDSEQ  250021125
2  FROMLVLPAT  250020754
3     TOCOMID    8627469
4    TOHYDSEQ  250020754

In [81]:
catch_char['metadata'].keys()

dict_keys(['FROMCOMID', 'FROMHYDSEQ', 'FROMLVLPAT', 'TOCOMID', 'TOHYDSEQ', 'TOLVLPAT', 'NODENUMBER', 'DELTALEVEL', 'DIRECTION', 'GAPDISTKM', 'HasGeo', 'TotDASqKM', 'DivDASqKM', 'Region', 'ComID', 'Fdate', 'StreamLeve', 'StreamOrde', 'StreamCalc', 'FromNode', 'ToNode', 'Hydroseq', 'LevelPathI', 'Pathlength', 'TerminalPa', 'Divergence', 'StartFlag', 'TerminalFl', 'DnLevel', 'ThinnerCod', 'UpLevelPat', 'UpHydroseq', 'DnLevelPat', 'DnMinorHyd', 'DnDrainCou', 'DnHydroseq', 'FromMeas', 'ToMeas', 'ReachCode', 'LengthKM', 'Fcode', 'RtnDiv', 'OutDiv', 'DivEffect', 'VPUIn', 'VPUOut', 'AreaSqKM', 'Tidal', 'TOTMA', 'WBAreaType', 'CentroidLatitude', 'CentroidLongitude', 'WBAREACOMI', 'MAXELEVRAW', 'MINELEVRAW', 'MAXELEVSMO', 'MINELEVSMO', 'SLOPE', 'ELEVFIXED', 'HWTYPE', 'STATUSFLAG', 'SLOPELENKM', 'COMID', 'REACHCODE', 'HUC12', 'TOHUC', 'Length', 'BANKFULL_WIDTH', 'BANKFULL_DEPTH', 'BANKFULL_XSEC_AREA'])

In [68]:
for key in catch_char['metadata']:
    print (key)

FROMCOMID
FROMHYDSEQ
FROMLVLPAT
TOCOMID
TOHYDSEQ
TOLVLPAT
NODENUMBER
DELTALEVEL
DIRECTION
GAPDISTKM
HasGeo
TotDASqKM
DivDASqKM
Region
ComID
Fdate
StreamLeve
StreamOrde
StreamCalc
FromNode
ToNode
Hydroseq
LevelPathI
Pathlength
TerminalPa
Divergence
StartFlag
TerminalFl
DnLevel
ThinnerCod
UpLevelPat
UpHydroseq
DnLevelPat
DnMinorHyd
DnDrainCou
DnHydroseq
FromMeas
ToMeas
ReachCode
LengthKM
Fcode
RtnDiv
OutDiv
DivEffect
VPUIn
VPUOut
AreaSqKM
Tidal
TOTMA
WBAreaType
CentroidLatitude
CentroidLongitude
WBAREACOMI
MAXELEVRAW
MINELEVRAW
MAXELEVSMO
MINELEVSMO
SLOPE
ELEVFIXED
HWTYPE
STATUSFLAG
SLOPELENKM
COMID
REACHCODE
HUC12
TOHUC
Length
BANKFULL_WIDTH
BANKFULL_DEPTH
BANKFULL_XSEC_AREA

In [72]:
for in ch_char['metadata']:
    print (value)

FROMCOMID
FROMHYDSEQ
FROMLVLPAT
TOCOMID
TOHYDSEQ
TOLVLPAT
NODENUMBER
DELTALEVEL
DIRECTION
GAPDISTKM
HasGeo
TotDASqKM
DivDASqKM
Region
ComID
Fdate
StreamLeve
StreamOrde
StreamCalc
FromNode
ToNode
Hydroseq
LevelPathI
Pathlength
TerminalPa
Divergence
StartFlag
TerminalFl
DnLevel
ThinnerCod
UpLevelPat
UpHydroseq
DnLevelPat
DnMinorHyd
DnDrainCou
DnHydroseq
FromMeas
ToMeas
ReachCode
LengthKM
Fcode
RtnDiv
OutDiv
DivEffect
VPUIn
VPUOut
AreaSqKM
Tidal
TOTMA
WBAreaType
CentroidLatitude
CentroidLongitude
WBAREACOMI
MAXELEVRAW
MINELEVRAW
MAXELEVSMO
MINELEVSMO
SLOPE
ELEVFIXED
HWTYPE
STATUSFLAG
SLOPELENKM
COMID
REACHCODE
HUC12
TOHUC
Length
BANKFULL_WIDTH
BANKFULL_DEPTH
BANKFULL_XSEC_AREA

In [135]:
catch_char['metadata'].keys()

dict_keys(['FROMCOMID', 'FROMHYDSEQ', 'FROMLVLPAT', 'TOCOMID', 'TOHYDSEQ', 'TOLVLPAT', 'NODENUMBER', 'DELTALEVEL', 'DIRECTION', 'GAPDISTKM', 'HasGeo', 'TotDASqKM', 'DivDASqKM', 'Region', 'ComID', 'Fdate', 'StreamLeve', 'StreamOrde', 'StreamCalc', 'FromNode', 'ToNode', 'Hydroseq', 'LevelPathI', 'Pathlength', 'TerminalPa', 'Divergence', 'StartFlag', 'TerminalFl', 'DnLevel', 'ThinnerCod', 'UpLevelPat', 'UpHydroseq', 'DnLevelPat', 'DnMinorHyd', 'DnDrainCou', 'DnHydroseq', 'FromMeas', 'ToMeas', 'ReachCode', 'LengthKM', 'Fcode', 'RtnDiv', 'OutDiv', 'DivEffect', 'VPUIn', 'VPUOut', 'AreaSqKM', 'Tidal', 'TOTMA', 'WBAreaType', 'CentroidLatitude', 'CentroidLongitude', 'WBAREACOMI', 'MAXELEVRAW', 'MINELEVRAW', 'MAXELEVSMO', 'MINELEVSMO', 'SLOPE', 'ELEVFIXED', 'HWTYPE', 'STATUSFLAG', 'SLOPELENKM', 'COMID', 'REACHCODE', 'HUC12', 'TOHUC', 'Length', 'BANKFULL_WIDTH', 'BANKFULL_DEPTH', 'BANKFULL_XSEC_AREA'])

In [94]:
df_nd_2[0:-1][:].values

array([['FROMCOMID', 'FROMHYDSEQ', 'FROMLVLPAT', 'TOCOMID', 'TOHYDSEQ',
        'TOLVLPAT', 'NODENUMBER', 'DELTALEVEL', 'DIRECTION', 'GAPDISTKM',
        'HasGeo', 'TotDASqKM', 'DivDASqKM', 'Region', 'ComID', 'Fdate',
        'StreamLeve', 'StreamOrde', 'StreamCalc', 'FromNode', 'ToNode',
        'Hydroseq', 'LevelPathI', 'Pathlength', 'TerminalPa',
        'Divergence', 'StartFlag', 'TerminalFl', 'DnLevel', 'ThinnerCod',
        'UpLevelPat', 'UpHydroseq', 'DnLevelPat', 'DnMinorHyd',
        'DnDrainCou', 'DnHydroseq', 'FromMeas', 'ToMeas', 'ReachCode',
        'LengthKM', 'Fcode', 'RtnDiv', 'OutDiv', 'DivEffect', 'VPUIn',
        'VPUOut', 'AreaSqKM', 'Tidal', 'TOTMA', 'WBAreaType',
        'CentroidLatitude', 'CentroidLongitude', 'WBAREACOMI',
        'MAXELEVRAW', 'MINELEVRAW', 'MAXELEVSMO', 'MINELEVSMO', 'SLOPE',
        'ELEVFIXED', 'HWTYPE', 'STATUSFLAG', 'SLOPELENKM', 'COMID',
        'REACHCODE', 'HUC12', 'TOHUC', 'Length', 'BANKFULL_WIDTH',
        'BANKFULL_DEPTH', 'BANKFULL_XSEC_AREA']], dtype=object)

In [95]:
key_list = [df_nd_2[0:-1][:].values]

In [122]:
key_list[:]

[array([['FROMCOMID', 'FROMHYDSEQ', 'FROMLVLPAT', 'TOCOMID', 'TOHYDSEQ',
         'TOLVLPAT', 'NODENUMBER', 'DELTALEVEL', 'DIRECTION', 'GAPDISTKM',
         'HasGeo', 'TotDASqKM', 'DivDASqKM', 'Region', 'ComID', 'Fdate',
         'StreamLeve', 'StreamOrde', 'StreamCalc', 'FromNode', 'ToNode',
         'Hydroseq', 'LevelPathI', 'Pathlength', 'TerminalPa',
         'Divergence', 'StartFlag', 'TerminalFl', 'DnLevel', 'ThinnerCod',
         'UpLevelPat', 'UpHydroseq', 'DnLevelPat', 'DnMinorHyd',
         'DnDrainCou', 'DnHydroseq', 'FromMeas', 'ToMeas', 'ReachCode',
         'LengthKM', 'Fcode', 'RtnDiv', 'OutDiv', 'DivEffect', 'VPUIn',
         'VPUOut', 'AreaSqKM', 'Tidal', 'TOTMA', 'WBAreaType',
         'CentroidLatitude', 'CentroidLongitude', 'WBAREACOMI',
         'MAXELEVRAW', 'MINELEVRAW', 'MAXELEVSMO', 'MINELEVSMO', 'SLOPE',
         'ELEVFIXED', 'HWTYPE', 'STATUSFLAG', 'SLOPELENKM', 'COMID',
         'REACHCODE', 'HUC12', 'TOHUC', 'Length', 'BANKFULL_WIDTH',
         'BANKFULL_DEPTH', 'BANKFULL_XSEC_AREA']], dtype=object)]

In [97]:
type(key_list)

list

In [125]:
df_test = pd.DataFrame(catch_char['metadata'].items()).transpose()

In [127]:
df_test[0:-1][:]

,0,1,2,3,4,5,6,7,8,9,...,60,61,62,63,64,65,66,67,68,69
0,FROMCOMID,FROMHYDSEQ,FROMLVLPAT,TOCOMID,TOHYDSEQ,TOLVLPAT,NODENUMBER,DELTALEVEL,DIRECTION,GAPDISTKM,...,STATUSFLAG,SLOPELENKM,COMID,REACHCODE,HUC12,TOHUC,Length,BANKFULL_WIDTH,BANKFULL_DEPTH,BANKFULL_XSEC_AREA

In [129]:
df_test.columns

RangeIndex(start=0, stop=70, step=1)

In [138]:
catch_char['metadata'].keys

In [136]:
len(catch_char['metadata'].keys())

70

In [140]:
df_test.columns = catch_char['metadata'].keys()
df_test[1:]

,FROMCOMID,FROMHYDSEQ,FROMLVLPAT,TOCOMID,TOHYDSEQ,TOLVLPAT,NODENUMBER,DELTALEVEL,DIRECTION,GAPDISTKM,...,STATUSFLAG,SLOPELENKM,COMID,REACHCODE,HUC12,TOHUC,Length,BANKFULL_WIDTH,BANKFULL_DEPTH,BANKFULL_XSEC_AREA
1,8625279,250021125,250020754,8627469,250020754,250020754,250007866,0,709,0,...,A,2.41,8625279,03010101000410,030101010405,030101010701,0.0,25.10,1.10,28.17

In [143]:
df_test_2 = df_test[1:]
df_test_2

,FROMCOMID,FROMHYDSEQ,FROMLVLPAT,TOCOMID,TOHYDSEQ,TOLVLPAT,NODENUMBER,DELTALEVEL,DIRECTION,GAPDISTKM,...,STATUSFLAG,SLOPELENKM,COMID,REACHCODE,HUC12,TOHUC,Length,BANKFULL_WIDTH,BANKFULL_DEPTH,BANKFULL_XSEC_AREA
1,8625279,250021125,250020754,8627469,250020754,250020754,250007866,0,709,0,...,A,2.41,8625279,03010101000410,030101010405,030101010701,0.0,25.10,1.10,28.17

In [43]:
#Your focus variables
data_2 = [(catch_char['metadata']['ComID'],catch_char['metadata']['BANKFULL_DEPTH'], catch_char['metadata']['BANKFULL_XSEC_AREA'], catch_char['metadata']['SLOPE'], catch_char['metadata']['BANKFULL_WIDTH'], catch_char['metadata']['LengthKM'])] 
data_2

[('8625279', '1.10', '28.17', '0.00255186', '25.10', '2.41')]

In [14]:
data_3 = [('COMID','StrDepth', 'StrSlope', 'StrXArea', 'StrWidth', 'StrLength'), (catch_char['metadata']['ComID'],catch_char['metadata']['BANKFULL_DEPTH'], catch_char['metadata']['BANKFULL_XSEC_AREA'], catch_char['metadata']['SLOPE'], catch_char['metadata']['BANKFULL_WIDTH'], catch_char['metadata']['LengthKM'])] 
data_3

[('COMID', 'StrDepth', 'StrSlope', 'StrXArea', 'StrWidth', 'StrLength'),
 ('6741978', '3.18', '380.72', '0.00001', '116.47', '1.123')]

In [175]:
df_all = pd.DataFrame()
for comid in comid_list:
    for i in range(length):
        print (comid[i])
        catch_char_url1 = ('https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=' + str(comid[i]))
        print(catch_char_url1)
        response2 = requests.get(catch_char_url1)
        catch_char1 = response2.json()
        #Specifying particular parameters
        #print (catch_char1['metadata']['ComID'],catch_char1['metadata']['BANKFULL_DEPTH'], catch_char1['metadata']['BANKFULL_XSEC_AREA'], catch_char1['metadata']['SLOPE'], catch_char1['metadata']['BANKFULL_WIDTH'], catch_char1['metadata']['LengthKM'])
        #data_f = [(catch_char1['metadata']['ComID'],catch_char1['metadata']['BANKFULL_DEPTH'], catch_char1['metadata']['BANKFULL_XSEC_AREA'], catch_char1['metadata']['SLOPE'], catch_char1['metadata']['BANKFULL_WIDTH'], catch_char1['metadata']['LengthKM'])]
        #Taking all data 
        df_test = pd.DataFrame(catch_char1['metadata'].items()).transpose()
        df_test.columns = catch_char1['metadata'].keys()
        #df_test[1:]
        df_test_2 = df_test[1:]
        df_all =  pd.concat([df_test_2, df_all])

8625279
https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8625279
8625313
https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8625313
8625375
https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8625375
8625523
https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8625523
8625547
https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8625547
8625615
https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8625615
8625685
https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8625685
8625697
https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8625697
8625717
https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8625717
8625727
https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8625727
8625731
https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8625731
8625735
https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8625735
8625739
https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8625739
8625747
https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8625747
8625775
https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8625775
8627469
https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8627469
8628577
https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8628577
8628579
https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8628579
8628581
https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8628581
8628587
https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8628587
8628591
https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8628591
8628603
https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8628603
8628611
https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8628611
8628623
https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8628623
8628627
https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8628627
8628631
https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8628631
8628641
https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8628641
8628643
https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8628643
8629331
https://ceamdev.ceeopdev.net/hms/rest/api/info/catchment?comid=8629331

In [176]:
df_all.head()

,FROMCOMID,FROMHYDSEQ,FROMLVLPAT,TOCOMID,TOHYDSEQ,TOLVLPAT,NODENUMBER,DELTALEVEL,DIRECTION,GAPDISTKM,...,STATUSFLAG,SLOPELENKM,COMID,REACHCODE,HUC12,TOHUC,Length,BANKFULL_WIDTH,BANKFULL_DEPTH,BANKFULL_XSEC_AREA
1,8629331,250033174,250020754,8628623,250031794,250020754,250008257,0,709,0,...,A,3.773,8629331,03010101000425,030101010405,030101010701,0.0,17.15,0.84,14.77
1,8628643,250093396,250020754,8628641,250071641,250020754,250008263,0,709,0,...,A,1.203,8628643,03010101000435,030101010405,030101010701,0.0,4.87,0.35,1.74
1,8628641,250071641,250020754,8628627,250060349,250020754,250008259,0,709,0,...,A,0.84,8628641,03010101000434,030101010405,030101010701,0.0,5.91,0.40,2.43
1,8628631,250132505,250020754,8628643,250093396,250020754,250008264,0,709,0,...,A,1.175,8628631,03010101000435,030101010405,030101010701,0.0,3.87,0.30,1.18
1,8628627,250060349,250020754,8628611,250053061,250020754,250008254,0,709,0,...,A,0.435,8628627,03010101000433,030101010405,030101010701,0.0,8.39,0.52,4.39

In [177]:
#df_all.to_csv('060223_BackCreek_COMID_HMS_Metadata.csv')

In [ ]:
df_all.info()

In [181]:
df_all['HUC12'].unique()

array(['030101010405'], dtype=object)

In [182]:
import requests

headers = {
    'accept': '*/*',
    'Content-Type': 'application/json-patch+json',
}

data = '{"runoffSource":"nldas","streamHydrology":"constant","aggregation":false,"source":"streamflow","dateTimeSpan":{"startDate":"2014-07-01T00:00:00","endDate":"2014-07-31T00:00:00","dateTimeFormat":"yyyy-MM-dd HH"},"geometry":{"description":null,"comID":0,"hucID":"030101010405","stationID":null,"point":null,"geometryMetadata":{"precipSource":"nldas"},"timezone":null},"dataValueFormat":"E3","temporalResolution":"default","timeLocalized":true,"units":"default","outputFormat":"json","baseURL":null,"inputTimeSeries":null}'

response = requests.post('https://ceamdev.ceeopdev.net/hms/rest/api/workflow/watershed', headers=headers, data=data)

In [183]:
output1 = response.json()

In [184]:
type(output1)

dict

In [185]:
output1.keys()

dict_keys(['dataset', 'dataSource', 'metadata', 'data', 'table'])

In [195]:
output1['metadata']

{'request_url': 'api/workflow/watershed',
 'start_date': '07/01/2014 01:00:00',
 'end_date': '08/08/2014 00:00:00',
 'timestep': 'daily',
 'errors': '',
 'catchments': '8625279,8627469,8625313,8625375,8625523,8625547,8625615,8625685,8625697,8625717,8625739,8625727,8625747,8625735,8625775,8625731,8628623,8629331,8628579,8628577,8628591,8628587,8628581,8628603,8628611,8628627,8628641,8628631,8628643,8625237,8627287,8625383,8625371,8625387,8625369,8625339,8625551,8625687,8625649,8625651,8625703,8625699,8629339,8625483,8628541,8628553,8628575,8628489,8628503,8628571,8628565,8628561,8628543,8628527,8628613,8628585,8628671,8628653,8628713,8628729,8628661,8628633,8628607,8628691,8628675,8629333,8628655,8625733,8625935,8625969,8625949,8625947,8627597,8625867,8626021,8625851,8625927,8625901,8625957,8625869,8625677,8625815,8625771,8625653',
 'connectivity_table_source': 'PlusFlowlineVAA',
 'NHDPlus_url': 'http://www.horizon-systems.com/nhdplus/NHDPlusV2_data.php',
 'Time_elapsed': '0.7646833333333334'}

In [196]:
output1['metadata']['catchments']

'8625279,8627469,8625313,8625375,8625523,8625547,8625615,8625685,8625697,8625717,8625739,8625727,8625747,8625735,8625775,8625731,8628623,8629331,8628579,8628577,8628591,8628587,8628581,8628603,8628611,8628627,8628641,8628631,8628643,8625237,8627287,8625383,8625371,8625387,8625369,8625339,8625551,8625687,8625649,8625651,8625703,8625699,8629339,8625483,8628541,8628553,8628575,8628489,8628503,8628571,8628565,8628561,8628543,8628527,8628613,8628585,8628671,8628653,8628713,8628729,8628661,8628633,8628607,8628691,8628675,8629333,8628655,8625733,8625935,8625969,8625949,8625947,8627597,8625867,8626021,8625851,8625927,8625901,8625957,8625869,8625677,8625815,8625771,8625653'

In [198]:
len(output1['metadata']['catchments']) # must use aqusition by by .loc or by single COMID and year as there are several hundred more sites

671

In [189]:
output1['dataset'] # will not use watershed workflow api. Will apply temp/precip/runoff annually per comid because of volume

'Precipitation, SurfaceRunoff, SubsurfaceRunoff, StreamHydrology'

In [188]:
output1.items()

dict_items([('dataset', 'Precipitation, SurfaceRunoff, SubsurfaceRunoff, StreamHydrology'), ('dataSource', 'nldas, nldas, nldas, constant'), ('metadata', {'request_url': 'api/workflow/watershed', 'start_date': '07/01/2014 01:00:00', 'end_date': '08/08/2014 00:00:00', 'timestep': 'daily', 'errors': '', 'catchments': '8625279,8627469,8625313,8625375,8625523,8625547,8625615,8625685,8625697,8625717,8625739,8625727,8625747,8625735,8625775,8625731,8628623,8629331,8628579,8628577,8628591,8628587,8628581,8628603,8628611,8628627,8628641,8628631,8628643,8625237,8627287,8625383,8625371,8625387,8625369,8625339,8625551,8625687,8625649,8625651,8625703,8625699,8629339,8625483,8628541,8628553,8628575,8628489,8628503,8628571,8628565,8628561,8628543,8628527,8628613,8628585,8628671,8628653,8628713,8628729,8628661,8628633,8628607,8628691,8628675,8629333,8628655,8625733,8625935,8625969,8625949,8625947,8627597,8625867,8626021,8625851,8625927,8625901,8625957,8625869,8625677,8625815,8625771,8625653', 'connectivity_table_source': 'PlusFlowlineVAA', 'NHDPlus_url': 'http://www.horizon-systems.com/nhdplus/NHDPlusV2_data.php', 'Time_elapsed': '0.7646833333333334'}), ('data', {'8625279': {'Precipitation': {'dataset': 'Precipitation', 'dataSource': 'nldas', 'metadata': {'request_time': '06/02/2023 16:13:59', 'column_1': 'Date (GMT) (GMT)', 'column_2': 'Precipitation', 'units': 'mm', 'Precipitation_sum': '60.513999999999996', 'Precipitation_mean': '1.952', 'Precipitation_max': '21.43', 'Precipitation_standard_deviation': '4.489', 'Precipitation_variance': '20.153', 'Precipitation_median': '0.071', 'Precipitation_entropy': '3.566', 'Precipitation_geometric_mean': '0', 'Precipitation_skewness': '3.418', 'Precipitation_root_mean_square': '4.828', 'Precipitation_99_percentile': '21.43', 'Precipitation_99_percentile_count': '1', 'Precipitation_95_percentile': '13.627', 'Precipitation_95_percentile_count': '1', 'Precipitation_75_percentile': '1.591', 'Precipitation_75_percentile_count': '8', 'Precipitation_zero_count': '12', 'timeseries_timezone': 'GMT'}, 'data': {'07/01/2014': ['0.139'], '07/02/2014': ['0.854'], '07/03/2014': ['21.43'], '07/04/2014': ['3.311'], '07/05/2014': ['0'], '07/06/2014': ['0'], '07/07/2014': ['0'], '07/08/2014': ['0'], '07/09/2014': ['12.76'], '07/10/2014': ['0.655'], '07/11/2014': ['1.361'], '07/12/2014': ['0'], '07/13/2014': ['1.73'], '07/14/2014': ['3.834'], '07/15/2014': ['1.637'], '07/16/2014': ['0'], '07/17/2014': ['0'], '07/18/2014': ['0.04'], '07/19/2014': ['0.731'], '07/20/2014': ['0'], '07/21/2014': ['0.604'], '07/22/2014': ['0.523'], '07/23/2014': ['0.006'], '07/24/2014': ['7.218'], '07/25/2014': ['0.071'], '07/26/2014': ['0'], '07/27/2014': ['3.608'], '07/28/2014': ['0'], '07/29/2014': ['0'], '07/30/2014': ['0'], '07/31/2014': ['0.002']}}, 'SurfaceRunoff': {'dataset': 'Runoff', 'dataSource': 'nldas', 'metadata': {'request_time': '06/02/2023 16:13:59', 'column_1': 'Date (GMT) (GMT)', 'column_2': 'Runoff', 'units': 'mm', 'Runoff_sum': '2.427', 'Runoff_mean': '0.078', 'Runoff_max': '1.439', 'Runoff_standard_deviation': '0.267', 'Runoff_variance': '0.071', 'Runoff_median': '0', 'Runoff_entropy': '1.979', 'Runoff_geometric_mean': '0', 'Runoff_skewness': '4.758', 'Runoff_root_mean_square': '0.274', 'Runoff_99_percentile': '1.439', 'Runoff_99_percentile_count': '1', 'Runoff_95_percentile': '0.444', 'Runoff_95_percentile_count': '1', 'Runoff_75_percentile': '0.007', 'Runoff_75_percentile_count': '8', 'Runoff_zero_count': '21', 'timeseries_timezone': 'GMT'}, 'data': {'07/01/2014': ['0'], '07/02/2014': ['0'], '07/03/2014': ['1.439'], '07/04/2014': ['0.193'], '07/05/2014': ['0'], '07/06/2014': ['0'], '07/07/2014': ['0'], '07/08/2014': ['0'], '07/09/2014': ['0.315'], '07/10/2014': ['0.002'], '07/11/2014': ['0.008'], '07/12/2014': ['0'], '07/13/2014': ['0.011'], '07/14/2014': ['0.035'], '07/15/2014': ['0.005'], '07/16/2014': ['0'], '07/17/2014': ['0'], '07/18/2014': ['0'], '07/19/2014': ['0'], '07/20/2014': ['0'], '07/21/2014': ['0'], '07/22/2014': ['0'], '07/23/2014': ['0'], '07/24/2014': ['0.334'], '07/25/2014': ['0'], '07/26/2014': ['0'], '07/27/2014': ['0.085'], '07/28/2014': ['0'], '07/29/2014': ['0'], '07/30/2014': ['0'], '07/31/2014': ['0']}}, 'SubsurfaceRunoff': {'dataset': 'Baseflow', 'dataSource': 'nldas', 'metadata': {'request_time': '06/02/2023 16:13:59', 'column_1': 'Date (GMT) (GMT)', 'column_2': 'Baseflow', 'units': 'mm', 'Baseflow_sum': '1.205', 'Baseflow_mean': '0.039', 'Baseflow_max': '0.072', 'Baseflow_standard_deviation': '0.017', 'Baseflow_variance': '0', 'Baseflow_median': '0.036', 'Baseflow_entropy': '4.761', 'Baseflow_geometric_mean': '0.035', 'Baseflow_skewness': '0.448', 'Baseflow_root_mean_square': '0.042', 'Baseflow_99_percentile': '0.072', 'Baseflow_99_percentile_count': '1', 'Baseflow_95_percentile': '0.071', 'Baseflow_95_percentile_count': '2', 'Baseflow_75_percentile': '0.052', 'Baseflow_75_percentile_count': '8', 'Baseflow_zero_count': '0', 'timeseries_timezone': 'GMT'}, 'data': {'07/01/2014': ['0.072'], '07/02/2014': ['0.071'], '07/03/2014': ['0.067'], '07/04/2014': ['0.066'], '07/05/2014': ['0.061'], '07/06/2014': ['0.057'], '07/07/2014': ['0.054'], '07/08/2014': ['0.052'], '07/09/2014': ['0.049'], '07/10/2014': ['0.048'], '07/11/2014': ['0.045'], '07/12/2014': ['0.043'], '07/13/2014': ['0.041'], '07/14/2014': ['0.04'], '07/15/2014': ['0.038'], '07/16/2014': ['0.036'], '07/17/2014': ['0.035'], '07/18/2014': ['0.033'], '07/19/2014': ['0.031'], '07/20/2014': ['0.031'], '07/21/2014': ['0.029'], '07/22/2014': ['0.026'], '07/23/2014': ['0.026'], '07/24/2014': ['0.024'], '07/25/2014': ['0.023'], '07/26/2014': ['0.022'], '07/27/2014': ['0.019'], '07/28/2014': ['0.019'], '07/29/2014': ['0.017'], '07/30/2014': ['0.016'], '07/31/2014': ['0.014']}}, 'StreamHydrology': {'dataset': 'Streamflow', 'dataSource': 'constant', 'metadata': {'request_time': '06/02/2023 16:13:59', 'column_1': 'Date (GMT)', 'column_2': 'Streamflow', 'units': 'm^3/sec'}, 'data': {'07/01/2014': ['0.279'], '07/02/2014': ['0.302'], '07/03/2014': ['17.441'], '07/04/2014': ['0.465'], '07/05/2014': ['0.301'], '07/06/2014': ['0.326'], '07/07/2014': ['0.343'], '07/08/2014': ['0.355'], '07/09/2014': ['1.894'], '07/10/2014': ['0.426'], '07/11/2014': ['0.42'], '07/12/2014': ['0.388'], '07/13/2014': ['0.394'], '07/14/2014': ['0.42'], '07/15/2014': ['0.427'], '07/16/2014': ['0.394'], '07/17/2014': ['0.378'], '07/18/2014': ['0.361'], '07/19/2014': ['0.369'], '07/20/2014': ['0.352'], '07/21/2014': ['0.338'], '07/22/2014': ['0.333'], '07/23/2014': ['0.304'], '07/24/2014': ['0.822'], '07/25/2014': ['0.282'], '07/26/2014': ['0.262'], '07/27/2014': ['0.714'], '07/28/2014': ['0.233'], '07/29/2014': ['0.216'], '07/30/2014': ['0.201'], '07/31/2014': ['0.186']}}}, '8627469': {'Precipitation': {'dataset': 'Precipitation', 'dataSource': 'nldas', 'metadata': {'request_time': '06/02/2023 16:13:59', 'column_1': 'Date (GMT) (GMT)', 'column_2': 'Precipitation', 'units': 'mm', 'Precipitation_sum': '60.513999999999996', 'Precipitation_mean': '1.952', 'Precipitation_max': '21.43', 'Precipitation_standard_deviation': '4.489', 'Precipitation_variance': '20.153', 'Precipitation_median': '0.071', 'Precipitation_entropy': '3.566', 'Precipitation_geometric_mean': '0', 'Precipitation_skewness': '3.418', 'Precipitation_root_mean_square': '4.828', 'Precipitation_99_percentile': '21.43', 'Precipitation_99_percentile_count': '1', 'Precipitation_95_percentile': '13.627', 'Precipitation_95_percentile_count': '1', 'Precipitation_75_percentile': '1.591', 'Precipitation_75_percentile_count': '8', 'Precipitation_zero_count': '12', 'timeseries_timezone': 'GMT'}, 'data': {'07/01/2014': ['0.139'], '07/02/2014': ['0.854'], '07/03/2014': ['21.43'], '07/04/2014': ['3.311'], '07/05/2014': ['0'], '07/06/2014': ['0'], '07/07/2014': ['0'], '07/08/2014': ['0'], '07/09/2014': ['12.76'], '07/10/2014': ['0.655'], '07/11/2014': ['1.361'], '07/12/2014': ['0'], '07/13/2014': ['1.73'], '07/14/2014': ['3.834'], '07/15/2014': ['1.637'], '07/16/2014': ['0'], '07/17/2014': ['0'], '07/18/2014': ['0.04'], '07/19/2014': ['0.731'], '07/20/2014': ['0'], '07/21/2014': ['0.604'], '07/22/2014': ['0.523'], '07/23/2014': ['0.006'], '07/24/2014': ['7.218'], '07/25/2014': ['0.071'], '07/26/2014': ['0'], '07/27/2014': ['3.608'], '07/28/2014': ['0'], '07/29/2014': ['0'], '07/30/2014': ['0'], '07/31/2014': ['0.002']}}, 'SurfaceRunoff': {'dataset': 'Runoff', 'dataSource': 'nldas', 'metadata': {'request_time': '06/02/2023 16:13:59', 'column_1': 'Date (GMT) (GMT)', 'column_2': 'Runoff', 'units': 'mm', 'Runoff_sum': '2.427', 'Runoff_mean': '0.078', 'Runoff_max': '1.439', 'Runoff_standard_deviation': '0.267', 'Runoff_variance': '0.071', 'Runoff_median': '0', 'Runoff_entropy': '1.979', 'Runoff_geometric_mean': '0', 'Runoff_skewness': '4.758', 'Runoff_root_mean_square': '0.274', 'Runoff_99_percentile': '1.439', 'Runoff_99_percentile_count': '1', 'Runoff_95_percentile': '0.444', 'Runoff_95_percentile_count': '1', 'Runoff_75_percentile': '0.007', 'Runoff_75_percentile_count': '8', 'Runoff_zero_count': '21', 'timeseries_timezone': 'GMT'}, 'data': {'07/01/2014': ['0'], '07/02/2014': ['0'], '07/03/2014': ['1.439'], '07/04/2014': ['0.193'], '07/05/2014': ['0'], '07/06/2014': ['0'], '07/07/2014': ['0'], '07/08/2014': ['0'], '07/09/2014': ['0.315'], '07/10/2014': ['0.002'], '07/11/2014': ['0.008'], '07/12/2014': ['0'], '07/13/2014': ['0.011'], '07/14/2014': ['0.035'], '07/15/2014': ['0.005'], '07/16/2014': ['0'], '07/17/2014': ['0'], '07/18/2014': ['0'], '07/19/2014': ['0'], '07/20/2014': ['0'], '07/21/2014': ['0'], '07/22/2014': ['0'], '07/23/2014': ['0'], '07/24/2014': ['0.334'], '07/25/2014': ['0'], '07/26/2014': ['0'], '07/27/2014': ['0.085'], '07/28/2014': ['0'], '07/29/2014': ['0'], '07/30/2014': ['0'], '07/31/2014': ['0']}}, 'SubsurfaceRunoff': {'dataset': 'Baseflow', 'dataSource': 'nldas', 'metadata': {'request_time': '06/02/2023 16:13:59', 'column_1': 'Date (GMT) (GMT)', 'column_2': 'Baseflow', 'units': 'mm', 'Baseflow_sum': '1.205', 'Baseflow_mean': '0.039', 'Baseflow_max': '0.072', 'Baseflow_standard_deviation': '0.017', 'Baseflow_variance': '0', 'Baseflow_median': '0.036', 'Baseflow_entropy': '4.761', 'Baseflow_geometric_mean': '0.035', 'Baseflow_skewness': '0.448', 'Baseflow_root_mean_square': '0.042', 'Baseflow_99_percentile': '0.072', 'Baseflow_99_percentile_count': '1', 'Baseflow_95_percentile': '0.071', 'Baseflow_95_percentile_count': '2', 'Baseflow_75_percentile': '0.052', 'Baseflow_75_percentile_count': '8', 'Baseflow_zero_count': '0', 'timeseries_timezone': 'GMT'}, 'data': {'07/01/2014': ['0.072'], '07/02/2014': ['0.071'], '07/03/2014': ['0.067'], '07/04/2014': ['0.066'], '07/05/2014': ['0.061'], '07/06/2014': ['0.057'], '07/07/2014': ['0.054'], '07/08/2014': ['0.052'], '07/09/2014': ['0.049'], '07/10/2014': ['0.048'], '07/11/2014': ['0.045'], '07/12/2014': ['0.043'], '07/13/2014': ['0.041'], '07/14/2014': ['0.04'], '07/15/2014': ['0.038'], '07/16/2014': ['0.036'], '07/17/2014': ['0.035'], '07/18/2014': ['0.033'], '07/19/2014': ['0.031'], '07/20/2014': ['0.031'], '07/21/2014': ['0.029'], '07/22/2014': ['0.026'], '07/23/2014': ['0.026'], '07/24/2014': ['0.024'], '07/25/2014': ['0.023'], '07/26/2014': ['0.022'], '07/27/2014': ['0.019'], '07/28/2014': ['0.019'], '07/29/2014': ['0.017'], '07/30/2014': ['0.016'], '07/31/2014': ['0.014']}}, 'StreamHydrology': {'dataset': 'Streamflow', 'dataSource': 'constant', 'metadata': {'request_time': '06/02/2023 16:13:59', 'column_1': 'Date (GMT)', 'column_2': 'Streamflow', 'units': 'm^3/sec'}, 'data': {'07/01/2014': ['0.279'], '07/02/2014': ['0.302'], '07/03/2014': ['17.441'], '07/04/2014': ['0.465'], '07/05/2014': ['0.301'], '07/06/2014': ['0.326'], '07/07/2014': ['0.343'], '07/08/2014': ['0.355'], '07/09/2014': ['1.894'], '07/10/2014': ['0.426'], '07/11/2014': ['0.42'], '07/12/2014': ['0.388'], '07/13/2014': ['0.394'], '07/14/2014': ['0.42'], '07/15/2014': ['0.427'], '07/16/2014': ['0.394'], '07/17/2014': ['0.378'], '07/18/2014': ['0.361'], '07/19/2014': ['0.369'], '07/20/2014': ['0.352'], '07/21/2014': ['0.338'], '07/22/2014': ['0.333'], '07/23/2014': ['0.304'], '07/24/2014': ['0.822'], '07/25/2014': ['0.282'], '07/26/2014': ['0.262'], '07/27/2014': ['0.714'], '07/28/2014': ['0.233'], '07/29/2014': ['0.216'], '07/30/2014': ['0.201'], '07/31/2014': ['0.186']}}}, '8625313': {'Precipitation': {'dataset': 'Precipitation', 'dataSource': 'nldas', 'metadata': {'request_time': '06/02/2023 16:13:59', 'column_1': 'Date (GMT) (GMT)', 'column_2': 'Precipitation', 'units': 'mm', 'Precipitation_sum': '60.513999999999996', 'Precipitation_mean': '1.952', 'Precipitation_max': '21.43', 'Precipitation_standard_deviation': '4.489', 'Precipitation_variance': '20.153', 'Precipitation_median': '0.071', 'Precipitation_entropy': '3.566', 'Precipitation_geometric_mean': '0', 'Precipitation_skewness': '3.418', 'Precipitation_root_mean_square': '4.828', 'Precipitation_99_percentile': '21.43', 'Precipitation_99_percentile_count': '1', 'Precipitation_95_percentile': '13.627', 'Precipitation_95_percentile_count': '1', 'Precipitation_75_percentile': '1.591', 'Precipitation_75_percentile_count': '8', 'Precipitation_zero_count': '12', 'timeseries_timezone': 'GMT'}, 'data': {'07/01/2014': ['0.139'], '07/02/2014': ['0.854'], '07/03/2014': ['21.43'], '07/04/2014': ['3.311'], '07/05/2014': ['0'], '07/06/2014': ['0'], '07/07/2014': ['0'], '07/08/2014': ['0'], '07/09/2014': ['12.76'], '07/10/2014': ['0.655'], '07/11/2014': ['1.361'], '07/12/2014': ['0'], '07/13/2014': ['1.73'], '07/14/2014': ['3.834'], '07/15/2014': ['1.637'], '07/16/2014': ['0'], '07/17/2014': ['0'], '07/18/2014': ['0.04'], '07/19/2014': ['0.731'], '07/20/2014': ['0'], '07/21/2014': ['0.604'], '07/22/2014': ['0.523'], '07/23/2014': ['0.006'], '07/24/2014': ['7.218'], '07/25/2014': ['0.071'], '07/26/2014': ['0'], '07/27/2014': ['3.608'], '07/28/2014': ['0'], '07/29/2014': ['0'], '07/30/2014': ['0'], '07/31/2014': ['0.002']}}, 'SurfaceRunoff': {'dataset': 'Runoff', 'dataSource': 'nldas', 'metadata': {'request_time': '06/02/2023 16:13:59', 'column_1': 'Date (GMT) (GMT)', 'column_2': 'Runoff', 'units': 'mm', 'Runoff_sum': '2.427', 'Runoff_mean': '0.078', 'Runoff_max': '1.439', 'Runoff_standard_deviation': '0.267', 'Runoff_variance': '0.071', 'Runoff_median': '0', 'Runoff_entropy': '1.979', 'Runoff_geometric_mean': '0', 'Runoff_skewness': '4.758', 'Runoff_root_mean_square': '0.274', 'Runoff_99_percentile': '1.439', 'Runoff_99_percentile_count': '1', 'Runoff_95_percentile': '0.444', 'Runoff_95_percentile_count': '1', 'Runoff_75_percentile': '0.007', 'Runoff_75_percentile_count': '8', 'Runoff_zero_count': '21', 'timeseries_timezone': 'GMT'}, 'data': {'07/01/2014': ['0'], '07/02/2014': ['0'], '07/03/2014': ['1.439'], '07/04/2014': ['0.193'], '07/05/2014': ['0'], '07/06/2014': ['0'], '07/07/2014': ['0'], '07/08/2014': ['0'], '07/09/2014': ['0.315'], '07/10/2014': ['0.002'], '07/11/2014': ['0.008'], '07/12/2014': ['0'], '07/13/2014': ['0.011'], '07/14/2014': ['0.035'], '07/15/2014': ['0.005'], '07/16/2014': ['0'], '07/17/2014': ['0'], '07/18/2014': ['0'], '07/19/2014': ['0'], '07/20/2014': ['0'], '07/21/2014': ['0'], '07/22/2014': ['0'], '07/23/2014': ['0'], '07/24/2014': ['0.334'], '07/25/2014': ['0'], '07/26/2014': ['0'], '07/27/2014': ['0.085'], '07/28/2014': ['0'], '07/29/2014': ['0'], '07/30/2014': ['0'], '07/31/2014': ['0']}}, 'SubsurfaceRunoff': {'dataset': 'Baseflow', 'dataSource': 'nldas', 'metadata': {'request_time': '06/02/2023 16:13:59', 'column_1': 'Date (GMT) (GMT)', 'column_2': 'Baseflow', 'units': 'mm', 'Baseflow_sum': '1.205', 'Baseflow_mean': '0.039', 'Baseflow_max': '0.072', 'Baseflow_standard_deviation': '0.017', 'Baseflow_variance': '0', 'Baseflow_median': '0.036', 'Baseflow_entropy': '4.761', 'Baseflow_geometric_mean': '0.035', 'Baseflow_skewness': '0.448', 'Baseflow_root_mean_square': '0.042', 'Baseflow_99_percentile': '0.072', 'Baseflow_99_percentile_count': '1', 'Baseflow_95_percentile': '0.071', 'Baseflow_95_percentile_count': '2', 'Baseflow_75_percentile': '0.052', 'Baseflow_75_percentile_count': '8', 'Baseflow_zero_count': '0', 'timeseries_timezone': 'GMT'}, 'data': {'07/01/2014': ['0.072'], '07/02/2014': ['0.071'], '07/03/2014': ['0.067'], '07/04/2014': ['0.066'], '07/05/2014': ['0.061'], '07/06/2014': ['0.057'], '07/07/2014': ['0.054'], '07/08/2014': ['0.052'], '07/09/2014': ['0.049'], '07/10/2014': ['0.048'], '07/11/2014': ['0.045'], '07/12/2014': ['0.043'], '07/13/2014': ['0.041'], '07/14/2014': ['0.04'], '07/15/2014': ['0.038'], '07/16/2014': ['0.036'], '07/17/2014': ['0.035'], '07/18/2014': ['0.033'], '07/19/2014': ['0.031'], '07/20/2014': ['0.031'], '07/21/2014': ['0.029'], '07/22/2014': ['0.026'], '07/23/2014': ['0.026'], '07/24/2014': ['0.024'], '07/25/2014': ['0.023'], '07/26/2014': ['0.022'], '07/27/2014': ['0.019'], '07/28/2014': ['0.019'], '07/29/2014': ['0.017'], '07/30/2014': ['0.016'], '07/31/2014': ['0.014']}}, 'StreamHydrology': {'dataset': 'Streamflow', 'dataSource': 'constant', 'metadata': {'request_time': '06/02/2023 16:13:59', 'column_1': 'Date (GMT)', 'column_2': 'Streamflow', 'units': 'm^3/sec'}, 'data': {'07/01/2014': ['0.271'], '07/02/2014': ['0.293'], '07/03/2014': ['17.076'], '07/04/2014': ['0.447'], '07/05/2014': ['0.294'], '07/06/2014': ['0.319'], '07/07/2014': ['0.336'], '07/08/2014': ['0.347'], '07/09/2014': ['1.843'], '07/10/2014': ['0.418'], '07/11/2014': ['0.411'], '07/12/2014': ['0.381'], '07/13/2014': ['0.386'], '07/14/2014': ['0.41'], '07/15/2014': ['0.418'], '07/16/2014': ['0.387'], '07/17/2014': ['0.371'], '07/18/2014': ['0.355'], '07/19/2014': ['0.362'], '07/20/2014': ['0.346'], '07/21/2014': ['0.332'], '07/22/2014': ['0.327'], '07/23/2014': ['0.298'], '07/24/2014': ['0.787'], '07/25/2014': ['0.277'], '07/26/2014': ['0.257'], '07/27/2014': ['0.695'], '07/28/2014': ['0.229'], '07/29/2014': ['0.212'], '07/30/2014': ['0.197'], '07/31/2014': ['0.183']}}}, '8625375': {'Precipitation': {'dataset': 'Precipitation', 'dataSource': 'nldas', 'metadata': {'request_time': '06/02/2023 16:13:59', 'column_1': 'Date (GMT) (GMT)', 'column_2': 'Precipitation', 'units': 'mm', 'Precipitation_sum': '90.12100000000002', 'Precipitation_mean': '2.907', 'Precipitation_max': '40.2', 'Precipitation_standard_deviation': '7.691', 'Precipitation_variance': '59.148', 'Precipitation_median': '0.01', 'Precipitation_entropy': '3.235', 'Precipitation_geometric_mean': '0', 'Precipitation_skewness': '4.231', 'Precipitation_root_mean_square': '8.105', 'Precipitation_99_percentile': '40.2', 'Precipitation_99_percentile_count': '1', 'Precipitation_95_percentile': '18.627', 'Precipitation_95_percentile_count': '1', 'Precipitation_75_percentile': '2.042', 'Precipitation_75_percentile_count': '8', 'Precipitation_zero_count': '14', 'timeseries_timezone': 'GMT'}, 'data': {'07/01/2014': ['0'], '07/02/2014': ['2.576'], '07/03/2014': ['40.2'], '07/04/2014': ['3.022'], '07/05/2014': ['0'], '07/06/2014': ['0'], '07/07/2014': ['0'], '07/08/2014': ['0'], '07/09/2014': ['16.23'], '07/10/2014': ['1.415'], '07/11/2014': ['1.86'], '07/12/2014': ['0'], '07/13/2014': ['1.146'], '07/14/2014': ['3.328'], '07/15/2014': ['2.078'], '07/16/2014': ['0'], '07/17/2014': ['0'], '07/18/2014': ['0.01'], '07/19/2014': ['1.45'], '07/20/2014': ['0'], '07/21/2014': ['1.149'], '07/22/2014': ['0.514'], '07/23/2014': ['0'], '07/24/2014': ['8.71'], '07/25/2014': ['0.144'], '07/26/2014': ['0'], '07/27/2014': ['6.283'], '07/28/2014': ['0'], '07/29/2014': ['0'], '07/30/2014': ['0'], '07/31/2014': ['0.006']}}, 'SurfaceRunoff': {'dataset': 'Runoff', 'dataSource': 'nldas', 'metadata': {'request_time': '06/02/2023 16:13:59', 'column_1': 'Date (GMT) (GMT)', 'column_2': 'Runoff', 'units': 'mm', 'Runoff_sum': '7.448', 'Runoff_mean': '0.24', 'Runoff_max': '5.93', 'Runoff_standard_deviation': '1.065', 'Runoff_variance': '1.135', 'Runoff_median': '0', 'Runoff_entropy': '2.468', 'Runoff_geometric_mean': '0', 'Runoff_skewness': '5.421', 'Runoff_root_mean_square': '1.075', 'Runoff_9

In [199]:
import datetime as dt

In [202]:
years = (2018 - 1981) +1
years

38

In [203]:
datetime_series = pd.date_range('1981-01-01', periods=years, freq='Y')
datetime_series #setting true date for acquistion period

DatetimeIndex(['1981-12-31', '1982-12-31', '1983-12-31', '1984-12-31',
               '1985-12-31', '1986-12-31', '1987-12-31', '1988-12-31',
               '1989-12-31', '1990-12-31', '1991-12-31', '1992-12-31',
               '1993-12-31', '1994-12-31', '1995-12-31', '1996-12-31',
               '1997-12-31', '1998-12-31', '1999-12-31', '2000-12-31',
               '2001-12-31', '2002-12-31', '2003-12-31', '2004-12-31',
               '2005-12-31', '2006-12-31', '2007-12-31', '2008-12-31',
               '2009-12-31', '2010-12-31', '2011-12-31', '2012-12-31',
               '2013-12-31', '2014-12-31', '2015-12-31', '2016-12-31',
               '2017-12-31', '2018-12-31'],
              dtype='datetime64[ns]', freq='A-DEC')

In [208]:
import numpy as np
import requests
import json
np_year = np.linspace(1981, 2018, num=years) #number is (year_last-year_1) + 1
int(np_year[0]) #first year in numpy array for year loop

1981

In [206]:
int(np_year[-1]) # last year

2018

In [216]:
type(new_list[0])

int

In [210]:
import pandas as pd
import numpy as np
import os

In [221]:
#condensed cleaned code for automation success using HMS 
df_focus_all = pd.DataFrame()
#correct accessibility of location list 
for comid in new_list:
    for year in np_year:
        start_year = int(year)
        start_date = str('1/1/') +str(start_year)
        end_date = str('12/31/') +str(start_year)
        #print(start_date, end_date)
        year_parse = pd.date_range(start=start_date, end=end_date, freq='D')
        #year_parse chunking to remove possible bottlenecks 
        print(year_parse.min(), year_parse.max()) #now in date time format for call in on api 
        #Temperature Conversion 
        data_temp_test = '{\n  "source": "nldas",\n  "dateTimeSpan": {\n    "startDate": "1998-01-01T00:00:00",\n    "endDate": "1998-12-31T00:00:00",\n    "dateTimeFormat": null\n  },\n  "geometry": {\n    "description": null,\n    "comID": 0,\n    "hucID": null,\n    "stationID": null,\n    "point": {\n      "latitude": null,\n      "longitude": null\n    },\n    "geometryMetadata": null,\n    "timezone": null\n  },\n  "dataValueFormat": "f2",\n  "temporalResolution": "daily",\n  "timeLocalized": false,\n  "units": null,\n  "outputFormat": null,\n  "baseURL": null,\n  "inputTimeSeries": null\n}'
        data_temp_input = json.loads(data_temp_test)
        data_temp_input['dateTimeSpan'].update(startDate= str(year_parse.min()), endDate= str(year_parse.max()))#permanent date change in scope
        data_temp_input['geometry']['comID'] = comid #correct for comid update
        #updated above comid acquistion rather than latitude and long by cell
        #data_temp_input['geometry']['point'].update({'latitude': str(df_2['lat'].iloc[(int(cell))]), 'longitude': str(df_2['long'].iloc[(int(cell))])}) #correct for point update
        data_temp_new = json.dumps(data_temp_input)
        #print(data_temp_new) 
        headers = {
        'accept': '*/*',
        'Content-Type': 'application/json-patch+json',
        }
        data = data_temp_new
        #qedcloud.net/hms
        response = requests.post('https://qedcloud.net/hms/rest/api/hydrology/temperature', headers=headers, data=data)
        print(comid)
        #response = requests.post('https://qed.epa.gov/hms/rest/api/hydrology/temperature', headers=headers, data=data)
        output1 = response.json()
        temp_all = output1['data']
        #for daymet data without Avg Temp daily column needs to be calculated in third column for code to work 
        #df_temp_all = pd.DataFrame.from_dict(temp_all, dtype=float, orient='index', columns=['Max Temp', 'Min Temp'] )
        #df_temp_all['Avg Temp'] = np.mean(df_temp_all.values, axis=1)
        #for nldas
        df_temp_all = pd.DataFrame.from_dict(temp_all, dtype=float, orient='index', columns=['Max Temp', 'Min Temp', 'Avg Temp'] )
        df_temp_all['C'] = df_temp_all['Avg Temp'] - 273.15
        df_temp_all['date']= pd.to_datetime(df_temp_all.index[:])
        #df_temp_all['year'] = df_temp_all.date.dt.year
        #df_temp_all['jday'] = df_temp_all.date.dt.day_of_year 
        # Completes Temperature (working correctly) may need to concatonate df rather than different xlsx
        df_focus = df_temp_all[['C']]
        df_focus.index = df_temp_all.index
        df_focus['COMID'] = comid #Will need to repartition by cell id later using df.loc
        df_focus.info()
        df_focus_all = pd.concat([df_focus, df_focus_all])
        df_focus_all.info() #for testing items in dataframe through iteration

1981-01-01 00:00:00 1981-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1982-01-01 00:00:00 1982-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1983-01-01 00:00:00 1983-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1984-01-01 00:00:00 1984-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1985-01-01 00:00:00 1985-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1986-01-01 00:00:00 1986-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1987-01-01 00:00:00 1987-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1988-01-01 00:00:00 1988-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1989-01-01 00:00:00 1989-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1990-01-01 00:00:00 1990-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1991-01-01 00:00:00 1991-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1992-01-01 00:00:00 1992-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1993-01-01 00:00:00 1993-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1994-01-01 00:00:00 1994-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1995-01-01 00:00:00 1995-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes

1996-01-01 00:00:00 1996-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1997-01-01 00:00:00 1997-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1998-01-01 00:00:00 1998-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1999-01-01 00:00:00 1999-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2000-01-01 00:00:00 2000-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2001-01-01 00:00:00 2001-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2002-01-01 00:00:00 2002-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2003-01-01 00:00:00 2003-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2004-01-01 00:00:00 2004-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2005-01-01 00:00:00 2005-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2006-01-01 00:00:00 2006-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2007-01-01 00:00:00 2007-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2008-01-01 00:00:00 2008-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2009-01-01 00:00:00 2009-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2010-01-01 00:00:00 2010-12-31 00:00:00

8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2011-01-01 00:00:00 2011-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2012-01-01 00:00:00 2012-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2013-01-01 00:00:00 2013-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2014-01-01 00:00:00 2014-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2015-01-01 00:00:00 2015-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2016-01-01 00:00:00 2016-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2017-01-01 00:00:00 2017-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2018-01-01 00:00:00 2018-12-31 00:00:00
8625279
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1981-01-01 00:00:00 1981-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1982-01-01 00:00:00 1982-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1983-01-01 00:00:00 1983-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1984-01-01 00:00:00 1984-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1985-01-01 00:00:00 1985-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1986-01-01 00:00:00 1986-12-31 00:00:00

8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1987-01-01 00:00:00 1987-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1988-01-01 00:00:00 1988-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1989-01-01 00:00:00 1989-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1990-01-01 00:00:00 1990-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1991-01-01 00:00:00 1991-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1992-01-01 00:00:00 1992-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1993-01-01 00:00:00 1993-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1994-01-01 00:00:00 1994-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1995-01-01 00:00:00 1995-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1996-01-01 00:00:00 1996-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1997-01-01 00:00:00 1997-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1998-01-01 00:00:00 1998-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1999-01-01 00:00:00 1999-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2000-01-01 00:00:00 2000-12-31 00:00:00

8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2001-01-01 00:00:00 2001-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2002-01-01 00:00:00 2002-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2003-01-01 00:00:00 2003-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2004-01-01 00:00:00 2004-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2005-01-01 00:00:00 2005-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2006-01-01 00:00:00 2006-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2007-01-01 00:00:00 2007-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2008-01-01 00:00:00 2008-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2009-01-01 00:00:00 2009-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2010-01-01 00:00:00 2010-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2011-01-01 00:00:00 2011-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2012-01-01 00:00:00 2012-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2013-01-01 00:00:00 2013-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2014-01-01 00:00:00 2014-12-31 00:00:00

8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2015-01-01 00:00:00 2015-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2016-01-01 00:00:00 2016-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2017-01-01 00:00:00 2017-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2018-01-01 00:00:00 2018-12-31 00:00:00
8625313
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1981-01-01 00:00:00 1981-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1982-01-01 00:00:00 1982-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1983-01-01 00:00:00 1983-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1984-01-01 00:00:00 1984-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1985-01-01 00:00:00 1985-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1986-01-01 00:00:00 1986-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1987-01-01 00:00:00 1987-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1988-01-01 00:00:00 1988-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1989-01-01 00:00:00 1989-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1990-01-01 00:00:00 1990-12-31 00:00:00

8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1991-01-01 00:00:00 1991-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1992-01-01 00:00:00 1992-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1993-01-01 00:00:00 1993-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1994-01-01 00:00:00 1994-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1995-01-01 00:00:00 1995-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1996-01-01 00:00:00 1996-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1997-01-01 00:00:00 1997-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1998-01-01 00:00:00 1998-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1999-01-01 00:00:00 1999-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2000-01-01 00:00:00 2000-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2001-01-01 00:00:00 2001-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2002-01-01 00:00:00 2002-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2003-01-01 00:00:00 2003-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2004-01-01 00:00:00 2004-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2005-01-01 00:00:00 2005-12-31 00:00:00

8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2006-01-01 00:00:00 2006-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2007-01-01 00:00:00 2007-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2008-01-01 00:00:00 2008-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2009-01-01 00:00:00 2009-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2010-01-01 00:00:00 2010-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2011-01-01 00:00:00 2011-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2012-01-01 00:00:00 2012-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2013-01-01 00:00:00 2013-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2014-01-01 00:00:00 2014-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2015-01-01 00:00:00 2015-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2016-01-01 00:00:00 2016-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2017-01-01 00:00:00 2017-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2018-01-01 00:00:00 2018-12-31 00:00:00
8625375
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1981-01-01 00:00:00 1981-12-31 00:00:00

8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1982-01-01 00:00:00 1982-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1983-01-01 00:00:00 1983-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1984-01-01 00:00:00 1984-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1985-01-01 00:00:00 1985-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1986-01-01 00:00:00 1986-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1987-01-01 00:00:00 1987-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1988-01-01 00:00:00 1988-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1989-01-01 00:00:00 1989-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1990-01-01 00:00:00 1990-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1991-01-01 00:00:00 1991-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1992-01-01 00:00:00 1992-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1993-01-01 00:00:00 1993-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1994-01-01 00:00:00 1994-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1995-01-01 00:00:00 1995-12-31 00:00:00

8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1996-01-01 00:00:00 1996-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1997-01-01 00:00:00 1997-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1998-01-01 00:00:00 1998-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1999-01-01 00:00:00 1999-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2000-01-01 00:00:00 2000-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2001-01-01 00:00:00 2001-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2002-01-01 00:00:00 2002-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2003-01-01 00:00:00 2003-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2004-01-01 00:00:00 2004-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2005-01-01 00:00:00 2005-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2006-01-01 00:00:00 2006-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2007-01-01 00:00:00 2007-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2008-01-01 00:00:00 2008-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2009-01-01 00:00:00 2009-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2010-01-01 00:00:00 2010-12-31 00:00:00

8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2011-01-01 00:00:00 2011-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2012-01-01 00:00:00 2012-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2013-01-01 00:00:00 2013-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2014-01-01 00:00:00 2014-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2015-01-01 00:00:00 2015-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2016-01-01 00:00:00 2016-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2017-01-01 00:00:00 2017-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2018-01-01 00:00:00 2018-12-31 00:00:00
8625523
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1981-01-01 00:00:00 1981-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1982-01-01 00:00:00 1982-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1983-01-01 00:00:00 1983-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1984-01-01 00:00:00 1984-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1985-01-01 00:00:00 1985-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1986-01-01 00:00:00 1986-12-31 00:00:00

8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1987-01-01 00:00:00 1987-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1988-01-01 00:00:00 1988-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1989-01-01 00:00:00 1989-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1990-01-01 00:00:00 1990-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1991-01-01 00:00:00 1991-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1992-01-01 00:00:00 1992-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1993-01-01 00:00:00 1993-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1994-01-01 00:00:00 1994-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1995-01-01 00:00:00 1995-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1996-01-01 00:00:00 1996-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1997-01-01 00:00:00 1997-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1998-01-01 00:00:00 1998-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1999-01-01 00:00:00 1999-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2000-01-01 00:00:00 2000-12-31 00:00:00

8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2001-01-01 00:00:00 2001-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2002-01-01 00:00:00 2002-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2003-01-01 00:00:00 2003-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2004-01-01 00:00:00 2004-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2005-01-01 00:00:00 2005-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2006-01-01 00:00:00 2006-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2007-01-01 00:00:00 2007-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2008-01-01 00:00:00 2008-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2009-01-01 00:00:00 2009-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2010-01-01 00:00:00 2010-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2011-01-01 00:00:00 2011-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2012-01-01 00:00:00 2012-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2013-01-01 00:00:00 2013-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2014-01-01 00:00:00 2014-12-31 00:00:00

8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2015-01-01 00:00:00 2015-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2016-01-01 00:00:00 2016-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2017-01-01 00:00:00 2017-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2018-01-01 00:00:00 2018-12-31 00:00:00
8625547
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1981-01-01 00:00:00 1981-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1982-01-01 00:00:00 1982-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1983-01-01 00:00:00 1983-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1984-01-01 00:00:00 1984-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1985-01-01 00:00:00 1985-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1986-01-01 00:00:00 1986-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1987-01-01 00:00:00 1987-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1988-01-01 00:00:00 1988-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1989-01-01 00:00:00 1989-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1990-01-01 00:00:00 1990-12-31 00:00:00

8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1991-01-01 00:00:00 1991-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1992-01-01 00:00:00 1992-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1993-01-01 00:00:00 1993-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1994-01-01 00:00:00 1994-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1995-01-01 00:00:00 1995-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1996-01-01 00:00:00 1996-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1997-01-01 00:00:00 1997-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1998-01-01 00:00:00 1998-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1999-01-01 00:00:00 1999-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2000-01-01 00:00:00 2000-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2001-01-01 00:00:00 2001-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2002-01-01 00:00:00 2002-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2003-01-01 00:00:00 2003-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2004-01-01 00:00:00 2004-12-31 00:00:00

8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2005-01-01 00:00:00 2005-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2006-01-01 00:00:00 2006-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2007-01-01 00:00:00 2007-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2008-01-01 00:00:00 2008-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2009-01-01 00:00:00 2009-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2010-01-01 00:00:00 2010-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2011-01-01 00:00:00 2011-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2012-01-01 00:00:00 2012-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2013-01-01 00:00:00 2013-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2014-01-01 00:00:00 2014-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2015-01-01 00:00:00 2015-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2016-01-01 00:00:00 2016-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2017-01-01 00:00:00 2017-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2018-01-01 00:00:00 2018-12-31 00:00:00
8625615
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1981-01-01 00:00:00 1981-12-31 00:00:00

8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1982-01-01 00:00:00 1982-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1983-01-01 00:00:00 1983-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1984-01-01 00:00:00 1984-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1985-01-01 00:00:00 1985-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1986-01-01 00:00:00 1986-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1987-01-01 00:00:00 1987-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1988-01-01 00:00:00 1988-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1989-01-01 00:00:00 1989-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1990-01-01 00:00:00 1990-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1991-01-01 00:00:00 1991-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1992-01-01 00:00:00 1992-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1993-01-01 00:00:00 1993-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1994-01-01 00:00:00 1994-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1995-01-01 00:00:00 1995-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1996-01-01 00:00:00 1996-12-31 00:00:00

8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1997-01-01 00:00:00 1997-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1998-01-01 00:00:00 1998-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1999-01-01 00:00:00 1999-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2000-01-01 00:00:00 2000-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2001-01-01 00:00:00 2001-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2002-01-01 00:00:00 2002-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2003-01-01 00:00:00 2003-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2004-01-01 00:00:00 2004-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2005-01-01 00:00:00 2005-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2006-01-01 00:00:00 2006-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2007-01-01 00:00:00 2007-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2008-01-01 00:00:00 2008-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2009-01-01 00:00:00 2009-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2010-01-01 00:00:00 2010-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2011-01-01 00:00:00 2011-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2012-01-01 00:00:00 2012-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2013-01-01 00:00:00 2013-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2014-01-01 00:00:00 2014-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2015-01-01 00:00:00 2015-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2016-01-01 00:00:00 2016-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2017-01-01 00:00:00 2017-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2018-01-01 00:00:00 2018-12-31 00:00:00
8625685
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1981-01-01 00:00:00 1981-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1982-01-01 00:00:00 1982-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1983-01-01 00:00:00 1983-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1984-01-01 00:00:00 1984-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1985-01-01 00:00:00 1985-12-31 00:00:00

8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1986-01-01 00:00:00 1986-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1987-01-01 00:00:00 1987-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1988-01-01 00:00:00 1988-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1989-01-01 00:00:00 1989-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1990-01-01 00:00:00 1990-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1991-01-01 00:00:00 1991-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1992-01-01 00:00:00 1992-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1993-01-01 00:00:00 1993-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1994-01-01 00:00:00 1994-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1995-01-01 00:00:00 1995-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1996-01-01 00:00:00 1996-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1997-01-01 00:00:00 1997-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1998-01-01 00:00:00 1998-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1999-01-01 00:00:00 1999-12-31 00:00:00

8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2000-01-01 00:00:00 2000-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2001-01-01 00:00:00 2001-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2002-01-01 00:00:00 2002-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2003-01-01 00:00:00 2003-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2004-01-01 00:00:00 2004-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2005-01-01 00:00:00 2005-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2006-01-01 00:00:00 2006-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2007-01-01 00:00:00 2007-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2008-01-01 00:00:00 2008-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2009-01-01 00:00:00 2009-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2010-01-01 00:00:00 2010-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2011-01-01 00:00:00 2011-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2012-01-01 00:00:00 2012-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2013-01-01 00:00:00 2013-12-31 00:00:00

8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2014-01-01 00:00:00 2014-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2015-01-01 00:00:00 2015-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2016-01-01 00:00:00 2016-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2017-01-01 00:00:00 2017-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2018-01-01 00:00:00 2018-12-31 00:00:00
8625697
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1981-01-01 00:00:00 1981-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1982-01-01 00:00:00 1982-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1983-01-01 00:00:00 1983-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1984-01-01 00:00:00 1984-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1985-01-01 00:00:00 1985-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1986-01-01 00:00:00 1986-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1987-01-01 00:00:00 1987-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1988-01-01 00:00:00 1988-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1989-01-01 00:00:00 1989-12-31 00:00:00

8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1990-01-01 00:00:00 1990-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1991-01-01 00:00:00 1991-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1992-01-01 00:00:00 1992-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1993-01-01 00:00:00 1993-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1994-01-01 00:00:00 1994-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1995-01-01 00:00:00 1995-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1996-01-01 00:00:00 1996-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1997-01-01 00:00:00 1997-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1998-01-01 00:00:00 1998-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1999-01-01 00:00:00 1999-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2000-01-01 00:00:00 2000-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2001-01-01 00:00:00 2001-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2002-01-01 00:00:00 2002-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2003-01-01 00:00:00 2003-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2004-01-01 00:00:00 2004-12-31 00:00:00

8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2005-01-01 00:00:00 2005-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2006-01-01 00:00:00 2006-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2007-01-01 00:00:00 2007-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2008-01-01 00:00:00 2008-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2009-01-01 00:00:00 2009-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2010-01-01 00:00:00 2010-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2011-01-01 00:00:00 2011-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2012-01-01 00:00:00 2012-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2013-01-01 00:00:00 2013-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2014-01-01 00:00:00 2014-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2015-01-01 00:00:00 2015-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2016-01-01 00:00:00 2016-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2017-01-01 00:00:00 2017-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2018-01-01 00:00:00 2018-12-31 00:00:00
8625717
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1981-01-01 00:00:00 1981-12-31 00:00:00

8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1982-01-01 00:00:00 1982-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1983-01-01 00:00:00 1983-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1984-01-01 00:00:00 1984-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1985-01-01 00:00:00 1985-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1986-01-01 00:00:00 1986-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1987-01-01 00:00:00 1987-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1988-01-01 00:00:00 1988-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1989-01-01 00:00:00 1989-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1990-01-01 00:00:00 1990-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1991-01-01 00:00:00 1991-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1992-01-01 00:00:00 1992-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1993-01-01 00:00:00 1993-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1994-01-01 00:00:00 1994-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1995-01-01 00:00:00 1995-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1996-01-01 00:00:00 1996-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1997-01-01 00:00:00 1997-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1998-01-01 00:00:00 1998-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1999-01-01 00:00:00 1999-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2000-01-01 00:00:00 2000-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2001-01-01 00:00:00 2001-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2002-01-01 00:00:00 2002-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2003-01-01 00:00:00 2003-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2004-01-01 00:00:00 2004-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2005-01-01 00:00:00 2005-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2006-01-01 00:00:00 2006-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2007-01-01 00:00:00 2007-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2008-01-01 00:00:00 2008-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2009-01-01 00:00:00 2009-12-31 00:00:00

8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2010-01-01 00:00:00 2010-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2011-01-01 00:00:00 2011-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2012-01-01 00:00:00 2012-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2013-01-01 00:00:00 2013-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2014-01-01 00:00:00 2014-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2015-01-01 00:00:00 2015-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2016-01-01 00:00:00 2016-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2017-01-01 00:00:00 2017-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2018-01-01 00:00:00 2018-12-31 00:00:00
8625727
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1981-01-01 00:00:00 1981-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1982-01-01 00:00:00 1982-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1983-01-01 00:00:00 1983-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1984-01-01 00:00:00 1984-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1985-01-01 00:00:00 1985-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1986-01-01 00:00:00 1986-12-31 00:00:00

8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1987-01-01 00:00:00 1987-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1988-01-01 00:00:00 1988-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1989-01-01 00:00:00 1989-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1990-01-01 00:00:00 1990-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1991-01-01 00:00:00 1991-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1992-01-01 00:00:00 1992-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1993-01-01 00:00:00 1993-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1994-01-01 00:00:00 1994-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1995-01-01 00:00:00 1995-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1996-01-01 00:00:00 1996-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1997-01-01 00:00:00 1997-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1998-01-01 00:00:00 1998-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1999-01-01 00:00:00 1999-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2000-01-01 00:00:00 2000-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2001-01-01 00:00:00 2001-12-31 00:00:00

8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2002-01-01 00:00:00 2002-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2003-01-01 00:00:00 2003-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2004-01-01 00:00:00 2004-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2005-01-01 00:00:00 2005-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2006-01-01 00:00:00 2006-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2007-01-01 00:00:00 2007-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2008-01-01 00:00:00 2008-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2009-01-01 00:00:00 2009-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2010-01-01 00:00:00 2010-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2011-01-01 00:00:00 2011-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2012-01-01 00:00:00 2012-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2013-01-01 00:00:00 2013-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2014-01-01 00:00:00 2014-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2015-01-01 00:00:00 2015-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2016-01-01 00:00:00 2016-12-31 00:00:00

8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2017-01-01 00:00:00 2017-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2018-01-01 00:00:00 2018-12-31 00:00:00
8625731
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1981-01-01 00:00:00 1981-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1982-01-01 00:00:00 1982-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1983-01-01 00:00:00 1983-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1984-01-01 00:00:00 1984-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1985-01-01 00:00:00 1985-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1986-01-01 00:00:00 1986-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1987-01-01 00:00:00 1987-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1988-01-01 00:00:00 1988-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1989-01-01 00:00:00 1989-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1990-01-01 00:00:00 1990-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1991-01-01 00:00:00 1991-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1992-01-01 00:00:00 1992-12-31 00:00:00

8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1993-01-01 00:00:00 1993-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1994-01-01 00:00:00 1994-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1995-01-01 00:00:00 1995-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1996-01-01 00:00:00 1996-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1997-01-01 00:00:00 1997-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1998-01-01 00:00:00 1998-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1999-01-01 00:00:00 1999-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2000-01-01 00:00:00 2000-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2001-01-01 00:00:00 2001-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2002-01-01 00:00:00 2002-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2003-01-01 00:00:00 2003-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2004-01-01 00:00:00 2004-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2005-01-01 00:00:00 2005-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2006-01-01 00:00:00 2006-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2007-01-01 00:00:00 2007-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2008-01-01 00:00:00 2008-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2009-01-01 00:00:00 2009-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2010-01-01 00:00:00 2010-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2011-01-01 00:00:00 2011-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2012-01-01 00:00:00 2012-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2013-01-01 00:00:00 2013-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2014-01-01 00:00:00 2014-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2015-01-01 00:00:00 2015-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2016-01-01 00:00:00 2016-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2017-01-01 00:00:00 2017-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2018-01-01 00:00:00 2018-12-31 00:00:00
8625735
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1981-01-01 00:00:00 1981-12-31 00:00:00

8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1982-01-01 00:00:00 1982-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1983-01-01 00:00:00 1983-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1984-01-01 00:00:00 1984-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1985-01-01 00:00:00 1985-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1986-01-01 00:00:00 1986-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1987-01-01 00:00:00 1987-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1988-01-01 00:00:00 1988-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1989-01-01 00:00:00 1989-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1990-01-01 00:00:00 1990-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1991-01-01 00:00:00 1991-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1992-01-01 00:00:00 1992-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1993-01-01 00:00:00 1993-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1994-01-01 00:00:00 1994-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1995-01-01 00:00:00 1995-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1996-01-01 00:00:00 1996-12-31 00:00:00

8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1997-01-01 00:00:00 1997-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1998-01-01 00:00:00 1998-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1999-01-01 00:00:00 1999-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2000-01-01 00:00:00 2000-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2001-01-01 00:00:00 2001-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2002-01-01 00:00:00 2002-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2003-01-01 00:00:00 2003-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2004-01-01 00:00:00 2004-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2005-01-01 00:00:00 2005-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2006-01-01 00:00:00 2006-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2007-01-01 00:00:00 2007-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2008-01-01 00:00:00 2008-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2009-01-01 00:00:00 2009-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2010-01-01 00:00:00 2010-12-31 00:00:00

8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2011-01-01 00:00:00 2011-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2012-01-01 00:00:00 2012-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2013-01-01 00:00:00 2013-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2014-01-01 00:00:00 2014-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2015-01-01 00:00:00 2015-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2016-01-01 00:00:00 2016-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2017-01-01 00:00:00 2017-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2018-01-01 00:00:00 2018-12-31 00:00:00
8625739
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1981-01-01 00:00:00 1981-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1982-01-01 00:00:00 1982-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1983-01-01 00:00:00 1983-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1984-01-01 00:00:00 1984-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1985-01-01 00:00:00 1985-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1986-01-01 00:00:00 1986-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1987-01-01 00:00:00 1987-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1988-01-01 00:00:00 1988-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1989-01-01 00:00:00 1989-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1990-01-01 00:00:00 1990-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1991-01-01 00:00:00 1991-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1992-01-01 00:00:00 1992-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1993-01-01 00:00:00 1993-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1994-01-01 00:00:00 1994-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1995-01-01 00:00:00 1995-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1996-01-01 00:00:00 1996-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1997-01-01 00:00:00 1997-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1998-01-01 00:00:00 1998-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1999-01-01 00:00:00 1999-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2000-01-01 00:00:00 2000-12-31 00:00:00

8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2001-01-01 00:00:00 2001-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2002-01-01 00:00:00 2002-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2003-01-01 00:00:00 2003-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2004-01-01 00:00:00 2004-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2005-01-01 00:00:00 2005-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2006-01-01 00:00:00 2006-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2007-01-01 00:00:00 2007-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2008-01-01 00:00:00 2008-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2009-01-01 00:00:00 2009-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2010-01-01 00:00:00 2010-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2011-01-01 00:00:00 2011-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2012-01-01 00:00:00 2012-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2013-01-01 00:00:00 2013-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2014-01-01 00:00:00 2014-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2015-01-01 00:00:00 2015-12-31 00:00:00

8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2016-01-01 00:00:00 2016-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2017-01-01 00:00:00 2017-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2018-01-01 00:00:00 2018-12-31 00:00:00
8625747
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1981-01-01 00:00:00 1981-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1982-01-01 00:00:00 1982-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1983-01-01 00:00:00 1983-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1984-01-01 00:00:00 1984-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1985-01-01 00:00:00 1985-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1986-01-01 00:00:00 1986-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1987-01-01 00:00:00 1987-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1988-01-01 00:00:00 1988-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1989-01-01 00:00:00 1989-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1990-01-01 00:00:00 1990-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1991-01-01 00:00:00 1991-12-31 00:00:00

8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1992-01-01 00:00:00 1992-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1993-01-01 00:00:00 1993-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1994-01-01 00:00:00 1994-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1995-01-01 00:00:00 1995-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1996-01-01 00:00:00 1996-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1997-01-01 00:00:00 1997-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1998-01-01 00:00:00 1998-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1999-01-01 00:00:00 1999-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2000-01-01 00:00:00 2000-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2001-01-01 00:00:00 2001-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2002-01-01 00:00:00 2002-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2003-01-01 00:00:00 2003-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2004-01-01 00:00:00 2004-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2005-01-01 00:00:00 2005-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2006-01-01 00:00:00 2006-12-31 00:00:00

8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2007-01-01 00:00:00 2007-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2008-01-01 00:00:00 2008-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2009-01-01 00:00:00 2009-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2010-01-01 00:00:00 2010-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2011-01-01 00:00:00 2011-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2012-01-01 00:00:00 2012-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2013-01-01 00:00:00 2013-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2014-01-01 00:00:00 2014-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2015-01-01 00:00:00 2015-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2016-01-01 00:00:00 2016-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2017-01-01 00:00:00 2017-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2018-01-01 00:00:00 2018-12-31 00:00:00
8625775
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1981-01-01 00:00:00 1981-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1982-01-01 00:00:00 1982-12-31 00:00:00

8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1983-01-01 00:00:00 1983-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1984-01-01 00:00:00 1984-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1985-01-01 00:00:00 1985-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1986-01-01 00:00:00 1986-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1987-01-01 00:00:00 1987-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1988-01-01 00:00:00 1988-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1989-01-01 00:00:00 1989-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1990-01-01 00:00:00 1990-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1991-01-01 00:00:00 1991-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1992-01-01 00:00:00 1992-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1993-01-01 00:00:00 1993-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1994-01-01 00:00:00 1994-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1995-01-01 00:00:00 1995-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1996-01-01 00:00:00 1996-12-31 00:00:00

8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1997-01-01 00:00:00 1997-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1998-01-01 00:00:00 1998-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1999-01-01 00:00:00 1999-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2000-01-01 00:00:00 2000-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2001-01-01 00:00:00 2001-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2002-01-01 00:00:00 2002-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2003-01-01 00:00:00 2003-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2004-01-01 00:00:00 2004-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2005-01-01 00:00:00 2005-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2006-01-01 00:00:00 2006-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2007-01-01 00:00:00 2007-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2008-01-01 00:00:00 2008-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2009-01-01 00:00:00 2009-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2010-01-01 00:00:00 2010-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2011-01-01 00:00:00 2011-12-31 00:00:00

8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2012-01-01 00:00:00 2012-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2013-01-01 00:00:00 2013-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2014-01-01 00:00:00 2014-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2015-01-01 00:00:00 2015-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2016-01-01 00:00:00 2016-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2017-01-01 00:00:00 2017-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2018-01-01 00:00:00 2018-12-31 00:00:00
8627469
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1981-01-01 00:00:00 1981-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1982-01-01 00:00:00 1982-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1983-01-01 00:00:00 1983-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1984-01-01 00:00:00 1984-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1985-01-01 00:00:00 1985-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1986-01-01 00:00:00 1986-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1987-01-01 00:00:00 1987-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1988-01-01 00:00:00 1988-12-31 00:00:00

8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1989-01-01 00:00:00 1989-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1990-01-01 00:00:00 1990-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1991-01-01 00:00:00 1991-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1992-01-01 00:00:00 1992-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1993-01-01 00:00:00 1993-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1994-01-01 00:00:00 1994-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1995-01-01 00:00:00 1995-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1996-01-01 00:00:00 1996-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1997-01-01 00:00:00 1997-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1998-01-01 00:00:00 1998-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1999-01-01 00:00:00 1999-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2000-01-01 00:00:00 2000-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2001-01-01 00:00:00 2001-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2002-01-01 00:00:00 2002-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2003-01-01 00:00:00 2003-12-31 00:00:00

8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2004-01-01 00:00:00 2004-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2005-01-01 00:00:00 2005-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2006-01-01 00:00:00 2006-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2007-01-01 00:00:00 2007-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2008-01-01 00:00:00 2008-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2009-01-01 00:00:00 2009-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2010-01-01 00:00:00 2010-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2011-01-01 00:00:00 2011-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2012-01-01 00:00:00 2012-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2013-01-01 00:00:00 2013-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2014-01-01 00:00:00 2014-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2015-01-01 00:00:00 2015-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2016-01-01 00:00:00 2016-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2017-01-01 00:00:00 2017-12-31 00:00:00
8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2018-01-01 00:00:00 2018-12-31 00:00:00

8628577
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1981-01-01 00:00:00 1981-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1982-01-01 00:00:00 1982-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1983-01-01 00:00:00 1983-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1984-01-01 00:00:00 1984-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1985-01-01 00:00:00 1985-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1986-01-01 00:00:00 1986-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1987-01-01 00:00:00 1987-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1988-01-01 00:00:00 1988-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1989-01-01 00:00:00 1989-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1990-01-01 00:00:00 1990-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1991-01-01 00:00:00 1991-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1992-01-01 00:00:00 1992-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1993-01-01 00:00:00 1993-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1994-01-01 00:00:00 1994-12-31 00:00:00

8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1995-01-01 00:00:00 1995-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1996-01-01 00:00:00 1996-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1997-01-01 00:00:00 1997-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1998-01-01 00:00:00 1998-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1999-01-01 00:00:00 1999-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2000-01-01 00:00:00 2000-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2001-01-01 00:00:00 2001-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2002-01-01 00:00:00 2002-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2003-01-01 00:00:00 2003-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2004-01-01 00:00:00 2004-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2005-01-01 00:00:00 2005-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2006-01-01 00:00:00 2006-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2007-01-01 00:00:00 2007-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2008-01-01 00:00:00 2008-12-31 00:00:00

8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2009-01-01 00:00:00 2009-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2010-01-01 00:00:00 2010-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2011-01-01 00:00:00 2011-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2012-01-01 00:00:00 2012-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2013-01-01 00:00:00 2013-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2014-01-01 00:00:00 2014-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2015-01-01 00:00:00 2015-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2016-01-01 00:00:00 2016-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2017-01-01 00:00:00 2017-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2018-01-01 00:00:00 2018-12-31 00:00:00
8628579
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1981-01-01 00:00:00 1981-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1982-01-01 00:00:00 1982-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1983-01-01 00:00:00 1983-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1984-01-01 00:00:00 1984-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1985-01-01 00:00:00 1985-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1986-01-01 00:00:00 1986-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1987-01-01 00:00:00 1987-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1988-01-01 00:00:00 1988-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1989-01-01 00:00:00 1989-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1990-01-01 00:00:00 1990-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1991-01-01 00:00:00 1991-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1992-01-01 00:00:00 1992-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1993-01-01 00:00:00 1993-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1994-01-01 00:00:00 1994-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1995-01-01 00:00:00 1995-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1996-01-01 00:00:00 1996-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1997-01-01 00:00:00 1997-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1998-01-01 00:00:00 1998-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1999-01-01 00:00:00 1999-12-31 00:00:00

8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2000-01-01 00:00:00 2000-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2001-01-01 00:00:00 2001-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2002-01-01 00:00:00 2002-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2003-01-01 00:00:00 2003-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2004-01-01 00:00:00 2004-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2005-01-01 00:00:00 2005-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2006-01-01 00:00:00 2006-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2007-01-01 00:00:00 2007-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2008-01-01 00:00:00 2008-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2009-01-01 00:00:00 2009-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2010-01-01 00:00:00 2010-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2011-01-01 00:00:00 2011-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2012-01-01 00:00:00 2012-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2013-01-01 00:00:00 2013-12-31 00:00:00

8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2014-01-01 00:00:00 2014-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2015-01-01 00:00:00 2015-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2016-01-01 00:00:00 2016-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2017-01-01 00:00:00 2017-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2018-01-01 00:00:00 2018-12-31 00:00:00
8628581
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1981-01-01 00:00:00 1981-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1982-01-01 00:00:00 1982-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1983-01-01 00:00:00 1983-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1984-01-01 00:00:00 1984-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1985-01-01 00:00:00 1985-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1986-01-01 00:00:00 1986-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1987-01-01 00:00:00 1987-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1988-01-01 00:00:00 1988-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1989-01-01 00:00:00 1989-12-31 00:00:00
8628587

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1990-01-01 00:00:00 1990-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1991-01-01 00:00:00 1991-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1992-01-01 00:00:00 1992-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1993-01-01 00:00:00 1993-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1994-01-01 00:00:00 1994-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1995-01-01 00:00:00 1995-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1996-01-01 00:00:00 1996-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1997-01-01 00:00:00 1997-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1998-01-01 00:00:00 1998-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1999-01-01 00:00:00 1999-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2000-01-01 00:00:00 2000-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2001-01-01 00:00:00 2001-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2002-01-01 00:00:00 2002-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2003-01-01 00:00:00 2003-12-31 00:00:00

8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2004-01-01 00:00:00 2004-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2005-01-01 00:00:00 2005-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2006-01-01 00:00:00 2006-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2007-01-01 00:00:00 2007-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2008-01-01 00:00:00 2008-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2009-01-01 00:00:00 2009-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2010-01-01 00:00:00 2010-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2011-01-01 00:00:00 2011-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2012-01-01 00:00:00 2012-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2013-01-01 00:00:00 2013-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2014-01-01 00:00:00 2014-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2015-01-01 00:00:00 2015-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2016-01-01 00:00:00 2016-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2017-01-01 00:00:00 2017-12-31 00:00:00
8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2018-01-01 00:00:00 2018-12-31 00:00:00

8628587
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1981-01-01 00:00:00 1981-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1982-01-01 00:00:00 1982-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1983-01-01 00:00:00 1983-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1984-01-01 00:00:00 1984-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1985-01-01 00:00:00 1985-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1986-01-01 00:00:00 1986-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1987-01-01 00:00:00 1987-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1988-01-01 00:00:00 1988-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1989-01-01 00:00:00 1989-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1990-01-01 00:00:00 1990-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1991-01-01 00:00:00 1991-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1992-01-01 00:00:00 1992-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1993-01-01 00:00:00 1993-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1994-01-01 00:00:00 1994-12-31 00:00:00

8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1995-01-01 00:00:00 1995-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1996-01-01 00:00:00 1996-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1997-01-01 00:00:00 1997-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1998-01-01 00:00:00 1998-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1999-01-01 00:00:00 1999-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2000-01-01 00:00:00 2000-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2001-01-01 00:00:00 2001-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2002-01-01 00:00:00 2002-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2003-01-01 00:00:00 2003-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2004-01-01 00:00:00 2004-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2005-01-01 00:00:00 2005-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2006-01-01 00:00:00 2006-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2007-01-01 00:00:00 2007-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2008-01-01 00:00:00 2008-12-31 00:00:00

8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2009-01-01 00:00:00 2009-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2010-01-01 00:00:00 2010-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2011-01-01 00:00:00 2011-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2012-01-01 00:00:00 2012-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2013-01-01 00:00:00 2013-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2014-01-01 00:00:00 2014-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2015-01-01 00:00:00 2015-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2016-01-01 00:00:00 2016-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2017-01-01 00:00:00 2017-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2018-01-01 00:00:00 2018-12-31 00:00:00
8628591
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1981-01-01 00:00:00 1981-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1982-01-01 00:00:00 1982-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1983-01-01 00:00:00 1983-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1984-01-01 00:00:00 1984-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1985-01-01 00:00:00 1985-12-31 00:00:00

8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1986-01-01 00:00:00 1986-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1987-01-01 00:00:00 1987-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1988-01-01 00:00:00 1988-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1989-01-01 00:00:00 1989-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1990-01-01 00:00:00 1990-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1991-01-01 00:00:00 1991-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1992-01-01 00:00:00 1992-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1993-01-01 00:00:00 1993-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1994-01-01 00:00:00 1994-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1995-01-01 00:00:00 1995-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1996-01-01 00:00:00 1996-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1997-01-01 00:00:00 1997-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1998-01-01 00:00:00 1998-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1999-01-01 00:00:00 1999-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2000-01-01 00:00:00 2000-12-31 00:00:00

8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2001-01-01 00:00:00 2001-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2002-01-01 00:00:00 2002-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2003-01-01 00:00:00 2003-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2004-01-01 00:00:00 2004-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2005-01-01 00:00:00 2005-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2006-01-01 00:00:00 2006-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2007-01-01 00:00:00 2007-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2008-01-01 00:00:00 2008-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2009-01-01 00:00:00 2009-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2010-01-01 00:00:00 2010-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2011-01-01 00:00:00 2011-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2012-01-01 00:00:00 2012-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2013-01-01 00:00:00 2013-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2014-01-01 00:00:00 2014-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2015-01-01 00:00:00 2015-12-31 00:00:00

8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2016-01-01 00:00:00 2016-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2017-01-01 00:00:00 2017-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2018-01-01 00:00:00 2018-12-31 00:00:00
8628603
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1981-01-01 00:00:00 1981-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1982-01-01 00:00:00 1982-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1983-01-01 00:00:00 1983-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1984-01-01 00:00:00 1984-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1985-01-01 00:00:00 1985-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1986-01-01 00:00:00 1986-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1987-01-01 00:00:00 1987-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1988-01-01 00:00:00 1988-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1989-01-01 00:00:00 1989-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1990-01-01 00:00:00 1990-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1991-01-01 00:00:00 1991-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1992-01-01 00:00:00 1992-12-31 00:00:00

8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1993-01-01 00:00:00 1993-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1994-01-01 00:00:00 1994-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1995-01-01 00:00:00 1995-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1996-01-01 00:00:00 1996-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1997-01-01 00:00:00 1997-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1998-01-01 00:00:00 1998-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1999-01-01 00:00:00 1999-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2000-01-01 00:00:00 2000-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2001-01-01 00:00:00 2001-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2002-01-01 00:00:00 2002-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2003-01-01 00:00:00 2003-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2004-01-01 00:00:00 2004-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2005-01-01 00:00:00 2005-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2006-01-01 00:00:00 2006-12-31 00:00:00

8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2007-01-01 00:00:00 2007-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2008-01-01 00:00:00 2008-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2009-01-01 00:00:00 2009-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2010-01-01 00:00:00 2010-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2011-01-01 00:00:00 2011-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2012-01-01 00:00:00 2012-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2013-01-01 00:00:00 2013-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2014-01-01 00:00:00 2014-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2015-01-01 00:00:00 2015-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2016-01-01 00:00:00 2016-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2017-01-01 00:00:00 2017-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2018-01-01 00:00:00 2018-12-31 00:00:00
8628611
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1981-01-01 00:00:00 1981-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1982-01-01 00:00:00 1982-12-31 00:00:00

8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1983-01-01 00:00:00 1983-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1984-01-01 00:00:00 1984-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1985-01-01 00:00:00 1985-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1986-01-01 00:00:00 1986-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1987-01-01 00:00:00 1987-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1988-01-01 00:00:00 1988-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1989-01-01 00:00:00 1989-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1990-01-01 00:00:00 1990-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1991-01-01 00:00:00 1991-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1992-01-01 00:00:00 1992-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1993-01-01 00:00:00 1993-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1994-01-01 00:00:00 1994-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1995-01-01 00:00:00 1995-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1996-01-01 00:00:00 1996-12-31 00:00:00

8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1997-01-01 00:00:00 1997-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1998-01-01 00:00:00 1998-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1999-01-01 00:00:00 1999-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2000-01-01 00:00:00 2000-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2001-01-01 00:00:00 2001-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2002-01-01 00:00:00 2002-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2003-01-01 00:00:00 2003-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2004-01-01 00:00:00 2004-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2005-01-01 00:00:00 2005-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2006-01-01 00:00:00 2006-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2007-01-01 00:00:00 2007-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2008-01-01 00:00:00 2008-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2009-01-01 00:00:00 2009-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2010-01-01 00:00:00 2010-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2011-01-01 00:00:00 2011-12-31 00:00:00

8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2012-01-01 00:00:00 2012-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2013-01-01 00:00:00 2013-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2014-01-01 00:00:00 2014-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2015-01-01 00:00:00 2015-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2016-01-01 00:00:00 2016-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2017-01-01 00:00:00 2017-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2018-01-01 00:00:00 2018-12-31 00:00:00
8628623
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1981-01-01 00:00:00 1981-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1982-01-01 00:00:00 1982-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1983-01-01 00:00:00 1983-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1984-01-01 00:00:00 1984-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1985-01-01 00:00:00 1985-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1986-01-01 00:00:00 1986-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1987-01-01 00:00:00 1987-12-31 00:00:00

8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1988-01-01 00:00:00 1988-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1989-01-01 00:00:00 1989-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1990-01-01 00:00:00 1990-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1991-01-01 00:00:00 1991-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1992-01-01 00:00:00 1992-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1993-01-01 00:00:00 1993-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1994-01-01 00:00:00 1994-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1995-01-01 00:00:00 1995-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1996-01-01 00:00:00 1996-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1997-01-01 00:00:00 1997-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1998-01-01 00:00:00 1998-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1999-01-01 00:00:00 1999-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2000-01-01 00:00:00 2000-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2001-01-01 00:00:00 2001-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2002-01-01 00:00:00 2002-12-31 00:00:00

8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2003-01-01 00:00:00 2003-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2004-01-01 00:00:00 2004-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2005-01-01 00:00:00 2005-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2006-01-01 00:00:00 2006-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2007-01-01 00:00:00 2007-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2008-01-01 00:00:00 2008-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2009-01-01 00:00:00 2009-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2010-01-01 00:00:00 2010-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2011-01-01 00:00:00 2011-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2012-01-01 00:00:00 2012-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2013-01-01 00:00:00 2013-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2014-01-01 00:00:00 2014-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2015-01-01 00:00:00 2015-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2016-01-01 00:00:00 2016-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2017-01-01 00:00:00 2017-12-31 00:00:00

8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2018-01-01 00:00:00 2018-12-31 00:00:00
8628627
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1981-01-01 00:00:00 1981-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1982-01-01 00:00:00 1982-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1983-01-01 00:00:00 1983-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1984-01-01 00:00:00 1984-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1985-01-01 00:00:00 1985-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1986-01-01 00:00:00 1986-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1987-01-01 00:00:00 1987-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1988-01-01 00:00:00 1988-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1989-01-01 00:00:00 1989-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1990-01-01 00:00:00 1990-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1991-01-01 00:00:00 1991-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1992-01-01 00:00:00 1992-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1993-01-01 00:00:00 1993-12-31 00:00:00

8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1994-01-01 00:00:00 1994-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1995-01-01 00:00:00 1995-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1996-01-01 00:00:00 1996-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1997-01-01 00:00:00 1997-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1998-01-01 00:00:00 1998-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1999-01-01 00:00:00 1999-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2000-01-01 00:00:00 2000-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2001-01-01 00:00:00 2001-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2002-01-01 00:00:00 2002-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2003-01-01 00:00:00 2003-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2004-01-01 00:00:00 2004-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2005-01-01 00:00:00 2005-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2006-01-01 00:00:00 2006-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2007-01-01 00:00:00 2007-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2008-01-01 00:00:00 2008-12-31 00:00:00

8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2009-01-01 00:00:00 2009-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2010-01-01 00:00:00 2010-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2011-01-01 00:00:00 2011-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2012-01-01 00:00:00 2012-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2013-01-01 00:00:00 2013-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2014-01-01 00:00:00 2014-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2015-01-01 00:00:00 2015-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2016-01-01 00:00:00 2016-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2017-01-01 00:00:00 2017-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2018-01-01 00:00:00 2018-12-31 00:00:00
8628631
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1981-01-01 00:00:00 1981-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1982-01-01 00:00:00 1982-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1983-01-01 00:00:00 1983-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1984-01-01 00:00:00 1984-12-31 00:00:00

8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1985-01-01 00:00:00 1985-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1986-01-01 00:00:00 1986-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1987-01-01 00:00:00 1987-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1988-01-01 00:00:00 1988-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1989-01-01 00:00:00 1989-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1990-01-01 00:00:00 1990-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1991-01-01 00:00:00 1991-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1992-01-01 00:00:00 1992-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1993-01-01 00:00:00 1993-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1994-01-01 00:00:00 1994-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1995-01-01 00:00:00 1995-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1996-01-01 00:00:00 1996-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1997-01-01 00:00:00 1997-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1998-01-01 00:00:00 1998-12-31 00:00:00

8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1999-01-01 00:00:00 1999-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2000-01-01 00:00:00 2000-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2001-01-01 00:00:00 2001-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2002-01-01 00:00:00 2002-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2003-01-01 00:00:00 2003-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2004-01-01 00:00:00 2004-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2005-01-01 00:00:00 2005-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2006-01-01 00:00:00 2006-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2007-01-01 00:00:00 2007-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2008-01-01 00:00:00 2008-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2009-01-01 00:00:00 2009-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2010-01-01 00:00:00 2010-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2011-01-01 00:00:00 2011-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2012-01-01 00:00:00 2012-12-31 00:00:00

8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2013-01-01 00:00:00 2013-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2014-01-01 00:00:00 2014-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2015-01-01 00:00:00 2015-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2016-01-01 00:00:00 2016-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2017-01-01 00:00:00 2017-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2018-01-01 00:00:00 2018-12-31 00:00:00
8628641
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1981-01-01 00:00:00 1981-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1982-01-01 00:00:00 1982-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1983-01-01 00:00:00 1983-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1984-01-01 00:00:00 1984-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1985-01-01 00:00:00 1985-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1986-01-01 00:00:00 1986-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1987-01-01 00:00:00 1987-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1988-01-01 00:00:00 1988-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1989-01-01 00:00:00 1989-12-31 00:00:00

8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1990-01-01 00:00:00 1990-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1991-01-01 00:00:00 1991-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1992-01-01 00:00:00 1992-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1993-01-01 00:00:00 1993-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1994-01-01 00:00:00 1994-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1995-01-01 00:00:00 1995-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1996-01-01 00:00:00 1996-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1997-01-01 00:00:00 1997-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1998-01-01 00:00:00 1998-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1999-01-01 00:00:00 1999-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2000-01-01 00:00:00 2000-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2001-01-01 00:00:00 2001-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2002-01-01 00:00:00 2002-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2003-01-01 00:00:00 2003-12-31 00:00:00

8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2004-01-01 00:00:00 2004-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2005-01-01 00:00:00 2005-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2006-01-01 00:00:00 2006-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2007-01-01 00:00:00 2007-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2008-01-01 00:00:00 2008-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2009-01-01 00:00:00 2009-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2010-01-01 00:00:00 2010-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2011-01-01 00:00:00 2011-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2012-01-01 00:00:00 2012-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2013-01-01 00:00:00 2013-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2014-01-01 00:00:00 2014-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2015-01-01 00:00:00 2015-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2016-01-01 00:00:00 2016-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2017-01-01 00:00:00 2017-12-31 00:00:00
8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2018-01-01 00:00:00 2018-12-31 00:00:00

8628643
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1981-01-01 00:00:00 1981-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1982-01-01 00:00:00 1982-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1983-01-01 00:00:00 1983-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1984-01-01 00:00:00 1984-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1985-01-01 00:00:00 1985-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1986-01-01 00:00:00 1986-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1987-01-01 00:00:00 1987-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1988-01-01 00:00:00 1988-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1989-01-01 00:00:00 1989-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1990-01-01 00:00:00 1990-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1991-01-01 00:00:00 1991-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1992-01-01 00:00:00 1992-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1993-01-01 00:00:00 1993-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1994-01-01 00:00:00 1994-12-31 00:00:00

8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1995-01-01 00:00:00 1995-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1996-01-01 00:00:00 1996-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1997-01-01 00:00:00 1997-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1998-01-01 00:00:00 1998-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
1999-01-01 00:00:00 1999-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2000-01-01 00:00:00 2000-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2001-01-01 00:00:00 2001-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2002-01-01 00:00:00 2002-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2003-01-01 00:00:00 2003-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2004-01-01 00:00:00 2004-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2005-01-01 00:00:00 2005-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2006-01-01 00:00:00 2006-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2007-01-01 00:00:00 2007-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2008-01-01 00:00:00 2008-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2009-01-01 00:00:00 2009-12-31 00:00:00

8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2010-01-01 00:00:00 2010-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2011-01-01 00:00:00 2011-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2012-01-01 00:00:00 2012-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2013-01-01 00:00:00 2013-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2014-01-01 00:00:00 2014-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2015-01-01 00:00:00 2015-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2016-01-01 00:00:00 2016-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2017-01-01 00:00:00 2017-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
2018-01-01 00:00:00 2018-12-31 00:00:00
8629331
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes
<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes

In [215]:
type(data_temp_input['geometry']['comID'])

int

In [222]:
df_focus_all.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C       0 non-null      float64
 1   COMID   0 non-null      int64
dtypes: float64(1), int64(1)
memory usage: 0.0+ bytes